In [32]:
import sqlalchemy as sqla
from sqlalchemy import create_engine
import traceback
import glob
import os
from pprint import pprint
#import simplejson as json
import requests
import time
from IPython.display import display

import pymysql

In [39]:
URI="dbbikes.cjk4ybuxtkwv.us-east-1.rds.amazonaws.com"
PORT="3306"
DB="dbbikes"
USER="cmcelduff"
PASSWORD="Tullamore1!"

In [42]:
#Connect to database
engine = create_engine("mysql+pymysql://{0}:{1}@{2}".format(USER, PASSWORD, URI), echo=True) 
connection = engine.connect()

2023-02-21 20:11:13,207 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2023-02-21 20:11:13,283 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-21 20:11:13,531 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2023-02-21 20:11:13,534 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-21 20:11:13,667 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2023-02-21 20:11:13,670 INFO sqlalchemy.engine.Engine [raw sql] {}

In [43]:
sql = """
CREATE DATABASE IF NOT EXISTS dbikes;
"""
engine.execute(sql)

2023-02-21 20:11:18,365 INFO sqlalchemy.engine.Engine
CREATE DATABASE IF NOT EXISTS dbikes;

2023-02-21 20:11:18,366 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-21 20:11:18,528 INFO sqlalchemy.engine.Engine COMMIT

In [44]:
# command to check database is running
for res in engine.execute("SHOW VARIABLES;"):
    print(res)

2023-02-21 20:11:41,443 INFO sqlalchemy.engine.Engine SHOW VARIABLES;
2023-02-21 20:11:41,444 INFO sqlalchemy.engine.Engine [raw sql] {}
('activate_all_roles_on_login', 'OFF')
('admin_address', '')
('admin_port', '33062')
('admin_ssl_ca', '')
('admin_ssl_capath', '')
('admin_ssl_cert', '')
('admin_ssl_cipher', '')
('admin_ssl_crl', '')
('admin_ssl_crlpath', '')
('admin_ssl_key', '')
('admin_tls_ciphersuites', '')
('admin_tls_version', 'TLSv1.2,TLSv1.3')
('authentication_policy', '*')
('auto_generate_certs', 'ON')
('auto_increment_increment', '1')
('auto_increment_offset', '1')
('autocommit', 'OFF')
('automatic_sp_privileges', 'ON')
('avoid_temporal_upgrade', 'OFF')
('awsauthenticationplugin_max_backoff_delay', '2000')
('awsauthenticationplugin_max_retry_count', '3')
('awsauthenticationplugin_retry_delay', '250')
('back_log', '61')
('basedir', '/rdsdbbin/mysql-8.0.28.R4/')
('big_tables', 'OFF')
('bind_address', '*')
('binlog_cache_size', '32768')
('binlog_checksum', 'CRC32')
('binlog_direct_non_transactional_updates', 'OFF')
('binlog_encryption', 'OFF')
('binlog_error_action', 'ABORT_SERVER')
('binlog_expire_logs_seconds', '2592000')
('binlog_format', 'MIXED')
('binlog_group_commit_sync_delay', '0')
('binlog_group_commit_sync_no_delay_count', '0')
('binlog_gtid_simple_recovery', 'ON')
('binlog_max_flush_queue_time', '0')
('binlog_order_commits', 'ON')
('binlog_rotate_encryption_master_key_at_startup', 'OFF')
('binlog_row_event_max_size', '8192')
('binlog_row_image', 'FULL')
('binlog_row_metadata', 'MINIMAL')
('binlog_row_value_options', '')
('binlog_rows_query_log_events', 'OFF')
('binlog_stmt_cache_size', '32768')
('binlog_transaction_compression', 'OFF')
('binlog_transaction_compression_level_zstd', '3')
('binlog_transaction_dependency_history_size', '25000')
('binlog_transaction_dependency_tracking', 'COMMIT_ORDER')
('block_encryption_mode', 'aes-128-ecb')
('bulk_insert_buffer_size', '8388608')
('caching_sha2_password_auto_generate_rsa_keys', 'ON')
('caching_sha2_password_digest_rounds', '5000')
('caching_sha2_password_private_key_path', 'private_key.pem')
('caching_sha2_password_public_key_path', 'public_key.pem')
('character_set_client', 'utf8mb4')
('character_set_connection', 'utf8mb4')
('character_set_database', 'utf8mb4')
('character_set_filesystem', 'binary')
('character_set_results', 'utf8mb4')
('character_set_server', 'utf8mb4')
('character_set_system', 'utf8mb3')
('character_sets_dir', '/rdsdbbin/mysql-8.0.28.R4/share/charsets/')
('check_proxy_users', 'OFF')
('collation_connection', 'utf8mb4_0900_ai_ci')
('collation_database', 'utf8mb4_0900_ai_ci')
('collation_server', 'utf8mb4_0900_ai_ci')
('completion_type', 'NO_CHAIN')
('concurrent_insert', 'AUTO')
('connect_timeout', '10')
('connection_memory_chunk_size', '8912')
('connection_memory_limit', '18446744073709551615')
('core_file', 'OFF')
('create_admin_listener_thread', 'OFF')
('cte_max_recursion_depth', '1000')
('datadir', '/rdsdbdata/db/')
('default_authentication_plugin', 'mysql_native_password')
('default_collation_for_utf8mb4', 'utf8mb4_0900_ai_ci')
('default_password_lifetime', '0')
('default_storage_engine', 'InnoDB')
('default_table_encryption', 'OFF')
('default_tmp_storage_engine', 'InnoDB')
('default_week_format', '0')
('delay_key_write', 'ON')
('delayed_insert_limit', '100')
('delayed_insert_timeout', '300')
('delayed_queue_size', '1000')
('disabled_storage_engines', '')
('disconnect_on_expired_password', 'ON')
('div_precision_increment', '4')
('end_markers_in_json', 'OFF')
('enforce_gtid_consistency', 'OFF')
('eq_range_index_dive_limit', '200')
('error_count', '0')
('event_scheduler', 'ON')
('expire_logs_days', '0')
('explicit_defaults_for_timestamp', 'ON')
('external_user', '')
('flush', 'OFF')
('flush_time', '0')
('foreign_key_checks', 'ON')
('ft_boolean_syntax', '+ -><()~*:""&|')
('ft_max_word_len', '84')
('ft_min_word_len', '4')
('ft_query_expansion_limit', '20')
('ft_stopword_file', '(built-in)')
('general_log', 'OFF')
('general_log_file', '/rdsdbdata/log/general/mysql-general.log')
('generated_random_password_length', '20')
('global_connection_memory_limit', '18446744073709551615')
('global_connection_memory_tracking', 'OFF')
('group_concat_max_len', '1024')
('group_replication_consistency', 'EVENTUAL')
('gtid_executed', '')
('gtid_executed_compression_period', '0')
('gtid_mode', 'OFF_PERMISSIVE')
('gtid_next', 'AUTOMATIC')
('gtid_owned', '')
('gtid_purged', '')
('have_compress', 'YES')
('have_dynamic_loading', 'YES')
('have_geometry', 'YES')
('have_openssl', 'YES')
('have_profiling', 'YES')
('have_query_cache', 'NO')
('have_rtree_keys', 'YES')
('have_ssl', 'YES')
('have_statement_timeout', 'YES')
('have_symlink', 'DISABLED')
('histogram_generation_max_mem_size', '20000000')
('host_cache_size', '189')
('hostname', 'ip-10-1-4-121')
('identity', '0')
('immediate_server_version', '999999')
('information_schema_stats_expiry', '86400')
('init_connect', '')
('init_file', '')
('init_replica', '')
('init_slave', '')
('innodb_adaptive_flushing', 'ON')
('innodb_adaptive_flushing_lwm', '10')
('innodb_adaptive_hash_index', 'ON')
('innodb_adaptive_hash_index_parts', '8')
('innodb_adaptive_max_sleep_delay', '150000')
('innodb_api_bk_commit_interval', '5')
('innodb_api_disable_rowlock', 'OFF')
('innodb_api_enable_binlog', 'OFF')
('innodb_api_enable_mdl', 'OFF')
('innodb_api_trx_level', '0')
('innodb_autoextend_increment', '64')
('innodb_autoinc_lock_mode', '2')
('innodb_buffer_pool_chunk_size', '134217728')
('innodb_buffer_pool_dump_at_shutdown', 'ON')
('innodb_buffer_pool_dump_now', 'OFF')
('innodb_buffer_pool_dump_pct', '25')
('innodb_buffer_pool_filename', 'ib_buffer_pool')
('innodb_buffer_pool_in_core_file', 'ON')
('innodb_buffer_pool_instances', '1')
('innodb_buffer_pool_load_abort', 'OFF')
('innodb_buffer_pool_load_at_startup', 'ON')
('innodb_buffer_pool_load_now', 'OFF')
('innodb_buffer_pool_size', '268435456')
('innodb_change_buffer_max_size', '25')
('innodb_change_buffering', 'all')
('innodb_checksum_algorithm', 'crc32')
('innodb_cmp_per_index_enabled', 'OFF')
('innodb_commit_concurrency', '0')
('innodb_compression_failure_threshold_pct', '5')
('innodb_compression_level', '6')
('innodb_compression_pad_pct_max', '50')
('innodb_concurrency_tickets', '5000')
('innodb_data_file_path', 'ibdata1:12M:autoextend')
('innodb_data_home_dir', '/rdsdbdata/db/innodb')
('innodb_ddl_buffer_size', '1048576')
('innodb_ddl_threads', '4')
('innodb_deadlock_detect', 'ON')
('innodb_dedicated_server', 'OFF')
('innodb_default_row_format', 'dynamic')
('innodb_directories', '')
('innodb_disable_sort_file_cache', 'OFF')
('innodb_doublewrite', 'ON')
('innodb_doublewrite_batch_size', '16')
('innodb_doublewrite_dir', '')
('innodb_doublewrite_files', '2')
('innodb_doublewrite_pages', '32')
('innodb_extend_and_initialize', 'ON')
('innodb_fast_shutdown', '1')
('innodb_file_per_table', 'ON')
('innodb_fill_factor', '100')
('innodb_flush_log_at_timeout', '1')
('innodb_flush_log_at_trx_commit', '1')
('innodb_flush_method', 'O_DIRECT')
('innodb_flush_neighbors', '0')
('innodb_flush_sync', 'ON')
('innodb_flushing_avg_loops', '30')
('innodb_force_load_corrupted', 'OFF')
('innodb_force_recovery', '0')
('innodb_fsync_threshold', '0')
('innodb_ft_aux_table', '')
('innodb_ft_cache_size', '8000000')
('innodb_ft_enable_diag_print', 'OFF')
('innodb_ft_enable_stopword', 'ON')
('innodb_ft_max_token_size', '84')
('innodb_ft_min_token_size', '3')
('innodb_ft_num_word_optimize', '2000')
('innodb_ft_result_cache_limit', '2000000000')
('innodb_ft_server_stopword_table', '')
('innodb_ft_sort_pll_degree', '2')
('innodb_ft_total_cache_size', '640000000')
('innodb_ft_user_stopword_table', '')
('innodb_idle_flush_pct', '100')
('innodb_io_capacity', '200')
('innodb_io_capacity_max', '2000')
('innodb_lock_wait_timeout', '50')
('innodb_log_buffer_size', '8388608')
('innodb_log_checksums', 'ON')
('innodb_log_compressed_pages', 'ON')
('innodb_log_file_size', '134217728')
('innodb_log_files_in_group', '2')
('innodb_log_group_home_dir', '/rdsdbdata/log/innodb')
('innodb_log_spin_cpu_abs_lwm', '80')
('innodb_log_spin_cpu_pct_hwm', '50')
('innodb_log_wait_for_flush_spin_hwm', '400')
('innodb_log_write_ahead_size', '8192')
('innodb_log_writer_threads', 'ON')
('innodb_lru_scan_depth', '1024')
('innodb_max_dirty_pages_pct', '90.000000')
('innodb_max_dirty_pages_pct_lwm', '10.000000')
('innodb_max_purge_lag', '0')
('innodb_max_purge_lag_delay', '0')
('innodb_max_undo_log_size', '1073741824')
('innodb_monitor_disable', '')
('innodb_monitor_enable', '')
('innodb_monitor_reset', '')
('innodb_monitor_reset_all', '')
('innodb_numa_interleave', 'OFF')
('innodb_old_blocks_pct', '37')
('innodb_old_blocks_time', '1000')
('innodb_online_alter_log_max_size', '134217728')
('innodb_open_files', '4000')
('innodb_optimize_fulltext_only', 'OFF')
('innodb_page_cleaners', '1')
('innodb_page_size', '16384')
('innodb_parallel_read_threads', '4')
('innodb_print_all_deadlocks', 'OFF')
('innodb_print_ddl_logs', 'OFF')
('innodb_purge_batch_size', '300')
('innodb_purge_rseg_truncate_frequency', '128')
('innodb_purge_threads', '1')
('innodb_random_read_ahead', 'OFF')
('innodb_read_ahead_threshold', '56')
('innodb_read_io_threads', '4')
('innodb_read_only', 'OFF')
('innodb_redo_log_archive_dirs', '')
('innodb_redo_log_encrypt', 'OFF')
('innodb_replication_delay', '0')
('innodb_rollback_on_timeout', 'OFF')
('innodb_rollback_segments', '128')
('innodb_segment_reserve_factor', '12.500000')
('innodb_sort_buffer_size', '1048576')
('innodb_spin_wait_delay', '6')
('innodb_spin_wait_pause_multiplier', '50')
('innodb_stats_auto_recalc', 'ON')
('innodb_stats_include_delete_marked', 'OFF')
('innodb_stats_method', 'nulls_equal')
('innodb_stats_on_metadata', 'OFF')
('innodb_stats_persistent', 'ON')
('innodb_stats_persistent_sample_pages', '20')
('innodb_stats_transient_sample_pages', '8')
('innodb_status_output', 'OFF')
('innodb_status_output_locks', 'OFF')
('innodb_strict_mode', 'ON')
('innodb_sync_array_size', '1')
('innodb_sync_spin_loops', '30')
('innodb_table_locks', 'ON')
('innodb_temp_data_file_path', 'ibtmp1:12M:autoextend')
('innodb_temp_tablespaces_dir', './#innodb_temp/')
('innodb_thread_concurrency', '0')
('innodb_thread_sleep_delay', '10000')
('innodb_tmpdir', '')
('innodb_undo_directory', './')
('innodb_undo_log_encrypt', 'OFF')
('innodb_undo_log_truncate', 'ON')
('innodb_undo_tablespaces', '2')
('innodb_use_fdatasync', 'OFF')
('innodb_use_native_aio', 'ON')
('innodb_validate_tablespace_paths', 'ON')
('innodb_version', '8.0.28')
('innodb_write_io_threads', '4')
('insert_id', '0')
('interactive_timeout', '28800')
('internal_tmp_mem_storage_engine', 'TempTable')
('join_buffer_size', '262144')
('keep_files_on_create', 'OFF')
('key_buffer_size', '16777216')
('key_cache_age_threshold', '300')
('key_cache_block_size', '1024')
('key_cache_division_limit', '100')
('keyring_operations', 'ON')
('large_files_support', 'ON')
('large_page_size', '0')
('large_pages', 'OFF')
('last_insert_id', '0')
('lc_messages', 'en_US')
('lc_messages_dir', '/rdsdbbin/mysql-8.0.28.R4/share/')
('lc_time_names', 'en_US')
('license', 'GPL')
('local_infile', 'ON')
('lock_wait_timeout', '31536000')
('locked_in_memory', 'OFF')
('log_bin', 'ON')
('log_bin_basename', '/rdsdbdata/log/binlog/mysql-bin-changelog')
('log_bin_index', '/rdsdbdata/log/binlog/mysql-bin-changelog.index')
('log_bin_trust_function_creators', 'OFF')
('log_bin_use_v1_row_events', 'OFF')
('log_error', '/rdsdbdata/log/error/mysql-error.log')
('log_error_services', 'log_filter_internal; log_sink_internal')
('log_error_suppression_list', '')
('log_error_verbosity', '2')
('log_output', 'TABLE')
('log_queries_not_using_indexes', 'OFF')
('log_raw', 'OFF')
('log_replica_updates', 'ON')
('log_slave_updates', 'ON')
('log_slow_admin_statements', 'OFF')
('log_slow_extra', 'OFF')
('log_slow_replica_statements', 'OFF')
('log_slow_slave_statements', 'OFF')
('log_statements_unsafe_for_binlog', 'OFF')
('log_throttle_queries_not_using_indexes', '0')
('log_timestamps', 'UTC')
('long_query_time', '10.000000')
('low_priority_updates', 'OFF')
('lower_case_file_system', 'OFF')
('lower_case_table_names', '0')
('mandatory_roles', '')
('master_info_repository', 'TABLE')
('master_verify_checksum', 'OFF')
('max_allowed_packet', '67108864')
('max_binlog_cache_size', '18446744073709547520')
('max_binlog_size', '134217728')
('max_binlog_stmt_cache_size', '18446744073709547520')
('max_connect_errors', '100')
('max_connections', '61')
('max_delayed_threads', '20')
('max_digest_length', '1024')
('max_error_count', '1024')
('max_execution_time', '0')
('max_heap_table_size', '16777216')
('max_insert_delayed_threads', '20')
('max_join_size', '18446744073709551615')
('max_length_for_sort_data', '4096')
('max_points_in_geometry', '65536')
('max_prepared_stmt_count', '16382')
('max_relay_log_size', '0')
('max_seeks_for_key', '18446744073709551615')
('max_sort_length', '1024')
('max_sp_recursion_depth', '0')
('max_user_connections', '0')
('max_write_lock_count', '18446744073709551615')
('min_examined_row_limit', '0')
('myisam_data_pointer_size', '6')
('myisam_max_sort_file_size', '9223372036853727232')
('myisam_mmap_size', '18446744073709551615')
('myisam_recover_options', 'OFF')
('myisam_repair_threads', '1')
('myisam_sort_buffer_size', '8388608')
('myisam_stats_method', 'nulls_unequal')
('myisam_use_mmap', 'OFF')
('mysql_native_password_proxy_users', 'OFF')
('net_buffer_length', '16384')
('net_read_timeout', '30')
('net_retry_count', '10')
('net_write_timeout', '60')
('new', 'OFF')
('ngram_token_size', '2')
('offline_mode', 'OFF')
('old', 'OFF')
('old_alter_table', 'OFF')
('open_files_limit', '1048576')
('optimizer_prune_level', '1')
('optimizer_search_depth', '62')
('optimizer_switch', 'index_merge=on,index_merge_union=on,index_merge_sort_union=on,index_merge_intersection=on,engine_condition_pushdown=on,index_condition_pushdown=on,mr ... (258 characters truncated) ... visible_indexes=off,skip_scan=on,hash_join=on,subquery_to_derived=off,prefer_ordering_index=on,hypergraph_optimizer=off,derived_condition_pushdown=on')
('optimizer_trace', 'enabled=off,one_line=off')
('optimizer_trace_features', 'greedy_search=on,range_optimizer=on,dynamic_range=on,repeated_subselect=on')
('optimizer_trace_limit', '1')
('optimizer_trace_max_mem_size', '1048576')
('optimizer_trace_offset', '-1')
('original_commit_timestamp', '36028797018963968')
('original_server_version', '999999')
('parser_max_mem_size', '18446744073709551615')
('partial_revokes', 'OFF')
('password_history', '0')
('password_require_current', 'OFF')
('password_reuse_interval', '0')
('performance_schema', 'OFF')
('performance_schema_accounts_size', '0')
('performance_schema_digests_size', '0')
('performance_schema_error_size', '0')
('performance_schema_events_stages_history_long_size', '0')
('performance_schema_events_stages_history_size', '0')
('performance_schema_events_statements_history_long_size', '0')
('performance_schema_events_statements_history_size', '0')
('performance_schema_events_transactions_history_long_size', '0')
('performance_schema_events_transactions_history_size', '0')
('performance_schema_events_waits_history_long_size', '0')
('performance_schema_events_waits_history_size', '0')
('performance_schema_hosts_size', '0')
('performance_schema_max_cond_classes', '0')
('performance_schema_max_cond_instances', '0')
('performance_schema_max_digest_length', '0')
('performance_schema_max_digest_sample_age', '60')
('performance_schema_max_file_classes', '0')
('performance_schema_max_file_handles', '0')
('performance_schema_max_file_instances', '0')
('performance_schema_max_index_stat', '0')
('performance_schema_max_memory_classes', '0')
('performance_schema_max_metadata_locks', '0')
('performance_schema_max_mutex_classes', '0')
('performance_schema_max_mutex_instances', '0')
('performance_schema_max_prepared_statements_instances', '0')
('performance_schema_max_program_instances', '0')
('performance_schema_max_rwlock_classes', '0')
('performance_schema_max_rwlock_instances', '0')
('performance_schema_max_socket_classes', '0')
('performance_schema_max_socket_instances', '0')
('performance_schema_max_sql_text_length', '0')
('performance_schema_max_stage_classes', '0')
('performance_schema_max_statement_classes', '0')
('performance_schema_max_statement_stack', '0')
('performance_schema_max_table_handles', '0')
('performance_schema_max_table_instances', '0')
('performance_schema_max_table_lock_stat', '0')
('performance_schema_max_thread_classes', '0')
('performance_schema_max_thread_instances', '0')
('performance_schema_session_connect_attrs_size', '0')
('performance_schema_setup_actors_size', '0')
('performance_schema_setup_objects_size', '0')
('performance_schema_show_processlist', 'OFF')
('performance_schema_users_size', '0')
('persist_only_admin_x509_subject', '')
('persisted_globals_load', 'OFF')
('pid_file', '/rdsdbdata/log/mysql-3306.pid')
('plugin_dir', '/rdsdbbin/mysql-8.0.28.R4/lib/plugin/')
('port', '3306')
('preload_buffer_size', '32768')
('print_identified_with_as_hex', 'OFF')
('profiling', 'OFF')
('profiling_history_size', '15')
('protocol_compression_algorithms', 'zlib,zstd,uncompressed')
('protocol_version', '10')
('proxy_user', '')
('pseudo_replica_mode', 'OFF')
('pseudo_slave_mode', 'OFF')
('pseudo_thread_id', '273')
('query_alloc_block_size', '8192')
('query_prealloc_size', '8192')
('rand_seed1', '0')
('rand_seed2', '0')
('range_alloc_block_size', '4096')
('range_optimizer_max_mem_size', '8388608')
('rbr_exec_mode', 'STRICT')
('read_buffer_size', '262144')
('read_only', 'OFF')
('read_rnd_buffer_size', '524288')
('regexp_stack_limit', '8000000')
('regexp_time_limit', '32')
('relay_log', '/rdsdbdata/log/relaylog/relaylog')
('relay_log_basename', '/rdsdbdata/log/relaylog/relaylog')
('relay_log_index', '/rdsdbdata/log/relaylog/relaylog.index')
('relay_log_info_file', 'relay-log.info')
('relay_log_info_repository', 'TABLE')
('relay_log_purge', 'ON')
('relay_log_recovery', 'ON')
('relay_log_space_limit', '0')
('replica_allow_batching', 'OFF')
('replica_checkpoint_group', '512')
('replica_checkpoint_period', '300')
('replica_compressed_protocol', 'OFF')
('replica_exec_mode', 'IDEMPOTENT')
('replica_load_tmpdir', '/rdsdbdata/tmp')
('replica_max_allowed_packet', '1073741824')
('replica_net_timeout', '60')
('replica_parallel_type', 'LOGICAL_CLOCK')
('replica_parallel_workers', '4')
('replica_pending_jobs_size_max', '134217728')
('replica_preserve_commit_order', 'ON')
('replica_skip_errors', 'OFF')
('replica_sql_verify_checksum', 'ON')
('replica_transaction_retries', '10')
('replica_type_conversions', '')
('replication_optimize_for_static_plugin_config', 'OFF')
('replication_sender_observe_commit_only', 'OFF')
('report_host', '')
('report_password', '')
('report_port', '3306')
('report_user', '')
('require_row_format', 'OFF')
('require_secure_transport', 'OFF')
('resultset_metadata', 'FULL')
('rpl_read_size', '8192')
('rpl_stop_replica_timeout', '31536000')
('rpl_stop_slave_timeout', '31536000')
('schema_definition_cache', '256')
('secondary_engine_cost_threshold', '100000.000000')
('secure_file_priv', '/secure_file_priv_dir/')
('select_into_buffer_size', '131072')
('select_into_disk_sync', 'OFF')
('select_into_disk_sync_delay', '0')
('server_id', '541196055')
('server_id_bits', '32')
('server_uuid', 'd9823ea1-b16c-11ed-9724-02c4f868e17d')
('session_track_gtids', 'OFF')
('session_track_schema', 'ON')
('session_track_state_change', 'OFF')
('session_track_system_variables', 'time_zone,autocommit,character_set_client,character_set_results,character_set_connection')
('session_track_transaction_info', 'OFF')
('sha256_password_auto_generate_rsa_keys', 'ON')
('sha256_password_private_key_path', 'private_key.pem')
('sha256_password_proxy_users', 'OFF')
('sha256_password_public_key_path', 'public_key.pem')
('show_create_table_skip_secondary_engine', 'OFF')
('show_create_table_verbosity', 'OFF')
('show_old_temporals', 'OFF')
('skip_external_locking', 'ON')
('skip_name_resolve', 'OFF')

In [45]:
sql_create_schema = "CREATE SCHEMA `dublin_bikes`;"
try:
    #res = engine.execute("DROP TABLE IF EXISTS station")
    res = engine.execute(sql_create_schema)
    print(res.fetchall())
except Exception as e:
    print(e)

2023-02-21 20:13:37,403 INFO sqlalchemy.engine.Engine CREATE SCHEMA `dublin_bikes`;
2023-02-21 20:13:37,406 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-21 20:13:37,550 INFO sqlalchemy.engine.Engine COMMIT
This result object does not return rows. It has been closed automatically.

In [47]:
# command to create table in mysql
sql_create_table = """
CREATE TABLE IF NOT EXISTS `dublin_bikes`.`station` (
address VARCHAR(256),
banking INTEGER,
bike_stands INTEGER,
bonus INTEGER,
contact_name VARCHAR(256),
name VARCHAR(256),
number INTEGER,
position_lat REAL,
position_lng REAL,
status VARCHAR(256)
)
"""

try:
    #res = engine.execute("DROP TABLE IF EXISTS station")
    res = engine.execute(sql)
    print(res.fetchall())
except Exception as e:
    print(e)

    # tom test 
    # tom test 2

2023-02-21 20:14:26,008 INFO sqlalchemy.engine.Engine
CREATE DATABASE IF NOT EXISTS dbikes;

2023-02-21 20:14:26,010 INFO sqlalchemy.engine.Engine [raw sql] {}
2023-02-21 20:14:26,147 INFO sqlalchemy.engine.Engine COMMIT
This result object does not return rows. It has been closed automatically.

In [49]:
NAME="Dublin"
STATIONS="https://api.jcdecaux.com/vls/v1/stations/"
DubBike_API = "7f06972a5ed335cf697379627fd13027274927c7"

def write_to_file(text):
    date_underscores = "{:%Y_%m_%d_%H_%M_%S}".format(datetime.datetime.now())
    with open(r"data\bikes_{}".format(date_underscores).replace(" ", "_"), "w") as f:
        f.write(text)

def stations_to_db(text):
    stations = json.loads(text)
    print(type(stations), len(stations))
    for station in stations:
        print(station)
        vals = (station.get("address"),int(station.get("banking")), int(station.get("bike_stands")), int(station.get("bonus")),station.get("contract_name"), station.get("name"), station.get("number"), station.get("position").get("lat"), station.get("position").get("lng"), station.get("status"))
        engine.execute("INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)", vals)
    return

def availability_to_db(text):
    stations = json.loads(text)
    #print(availability)
    for station in stations:
        #print(station.get("name"))
        #print(station.get("number"))
        #print(station.get("available_bikes"))
        #print(station.get("available_bike_stands"))
        #print(station.get("last_update"))
        vals = (int(station.get("number")), int(station.get("available_bikes")), int(station.get("available_bike_stands")), int(station.get("last_update")))
        engine.execute("INSERT INTO `dublin_bikes`.`availability` values(%s,%s,%s,%s)", vals)
    return
        
                                            
def main():
    print(os.path)
    while True:
        try:
            now = datetime.datetime.now()
            r = requests.get(STATIONS, params={"apiKey": DubBike_API, "contract" : NAME})
            print(r, now)
            write_to_file(r.text)
            stations_to_db(r.text)
            availability_to_db(r.text)
            time.sleep(5*60)
        except:
            print(traceback.format_exc())
            #if engine is None:
                #pass
        return

if __name__== "__main__":
    main()

<module 'posixpath' from '/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/posixpath.py'>
<Response [200]> 2023-02-21 20:17:28.401856
<class 'list'> 114
{'number': 42, 'contract_name': 'dublin', 'name': 'SMITHFIELD NORTH', 'address': 'Smithfield North', 'position': {'lat': 53.349562, 'lng': -6.278198}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 1, 'available_bikes': 29, 'status': 'OPEN', 'last_update': 1677010068000}
2023-02-21 20:17:28,842 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:28,844 INFO sqlalchemy.engine.Engine [raw sql] ('Smithfield North', 0, 30, 0, 'dublin', 'SMITHFIELD NORTH', 42, 53.349562, -6.278198, 'OPEN')
2023-02-21 20:17:28,990 INFO sqlalchemy.engine.Engine COMMIT
{'number': 30, 'contract_name': 'dublin', 'name': 'PARNELL SQUARE NORTH', 'address': 'Parnell Square North', 'position': {'lat': 53.3537415547453, 'lng': -6.26530144781526}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 18, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010052000}
2023-02-21 20:17:29,246 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:29,248 INFO sqlalchemy.engine.Engine [raw sql] ('Parnell Square North', 0, 20, 0, 'dublin', 'PARNELL SQUARE NORTH', 30, 53.3537415547453, -6.26530144781526, 'OPEN')
2023-02-21 20:17:29,372 INFO sqlalchemy.engine.Engine COMMIT
{'number': 54, 'contract_name': 'dublin', 'name': 'CLONMEL STREET', 'address': 'Clonmel Street', 'position': {'lat': 53.336021, 'lng': -6.26298}, 'banking': False, 'bonus': False, 'bike_stands': 33, 'available_bike_stands': 27, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010624000}
2023-02-21 20:17:29,626 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:29,627 INFO sqlalchemy.engine.Engine [raw sql] ('Clonmel Street', 0, 33, 0, 'dublin', 'CLONMEL STREET', 54, 53.336021, -6.26298, 'OPEN')
2023-02-21 20:17:29,751 INFO sqlalchemy.engine.Engine COMMIT
{'number': 108, 'contract_name': 'dublin', 'name': 'AVONDALE ROAD', 'address': 'Avondale Road', 'position': {'lat': 53.359405, 'lng': -6.276142}, 'banking': False, 'bonus': False, 'bike_stands': 35, 'available_bike_stands': 20, 'available_bikes': 15, 'status': 'OPEN', 'last_update': 1677010205000}
2023-02-21 20:17:30,006 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:30,006 INFO sqlalchemy.engine.Engine [raw sql] ('Avondale Road', 0, 35, 0, 'dublin', 'AVONDALE ROAD', 108, 53.359405, -6.276142, 'OPEN')
2023-02-21 20:17:30,129 INFO sqlalchemy.engine.Engine COMMIT
{'number': 20, 'contract_name': 'dublin', 'name': 'JAMES STREET EAST', 'address': 'James Street East', 'position': {'lat': 53.336597, 'lng': -6.248109}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 27, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010117000}
2023-02-21 20:17:30,377 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:30,379 INFO sqlalchemy.engine.Engine [raw sql] ('James Street East', 0, 30, 0, 'dublin', 'JAMES STREET EAST', 20, 53.336597, -6.248109, 'OPEN')
2023-02-21 20:17:30,502 INFO sqlalchemy.engine.Engine COMMIT
{'number': 56, 'contract_name': 'dublin', 'name': 'MOUNT STREET LOWER', 'address': 'Mount Street Lower', 'position': {'lat': 53.33796, 'lng': -6.24153}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 37, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010421000}
2023-02-21 20:17:30,759 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:30,761 INFO sqlalchemy.engine.Engine [raw sql] ('Mount Street Lower', 0, 40, 0, 'dublin', 'MOUNT STREET LOWER', 56, 53.33796, -6.24153, 'OPEN')
2023-02-21 20:17:30,887 INFO sqlalchemy.engine.Engine COMMIT
{'number': 6, 'contract_name': 'dublin', 'name': 'CHRISTCHURCH PLACE', 'address': 'Christchurch Place', 'position': {'lat': 53.343368, 'lng': -6.27012}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 14, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010617000}
2023-02-21 20:17:31,141 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:31,143 INFO sqlalchemy.engine.Engine [raw sql] ('Christchurch Place', 0, 20, 0, 'dublin', 'CHRISTCHURCH PLACE', 6, 53.343368, -6.27012, 'OPEN')
2023-02-21 20:17:31,266 INFO sqlalchemy.engine.Engine COMMIT
{'number': 18, 'contract_name': 'dublin', 'name': 'GRANTHAM STREET', 'address': 'Grantham Street', 'position': {'lat': 53.334123, 'lng': -6.265436}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 5, 'available_bikes': 25, 'status': 'OPEN', 'last_update': 1677010637000}
2023-02-21 20:17:31,512 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:31,514 INFO sqlalchemy.engine.Engine [raw sql] ('Grantham Street', 0, 30, 0, 'dublin', 'GRANTHAM STREET', 18, 53.334123, -6.265436, 'OPEN')
2023-02-21 20:17:31,635 INFO sqlalchemy.engine.Engine COMMIT
{'number': 32, 'contract_name': 'dublin', 'name': 'PEARSE STREET', 'address': 'Pearse Street', 'position': {'lat': 53.344304, 'lng': -6.250427}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 0, 'available_bikes': 30, 'status': 'OPEN', 'last_update': 1677010588000}
2023-02-21 20:17:31,893 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:31,895 INFO sqlalchemy.engine.Engine [raw sql] ('Pearse Street', 0, 30, 0, 'dublin', 'PEARSE STREET', 32, 53.344304, -6.250427, 'OPEN')
2023-02-21 20:17:32,023 INFO sqlalchemy.engine.Engine COMMIT
{'number': 52, 'contract_name': 'dublin', 'name': 'YORK STREET EAST', 'address': 'York Street East', 'position': {'lat': 53.338755, 'lng': -6.262003}, 'banking': False, 'bonus': False, 'bike_stands': 32, 'available_bike_stands': 28, 'available_bikes': 4, 'status': 'OPEN', 'last_update': 1677010057000}
2023-02-21 20:17:32,275 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:32,277 INFO sqlalchemy.engine.Engine [raw sql] ('York Street East', 0, 32, 0, 'dublin', 'YORK STREET EAST', 52, 53.338755, -6.262003, 'OPEN')
2023-02-21 20:17:32,399 INFO sqlalchemy.engine.Engine COMMIT
{'number': 48, 'contract_name': 'dublin', 'name': 'EXCISE WALK', 'address': 'Excise Walk', 'position': {'lat': 53.347777, 'lng': -6.244239}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 24, 'available_bikes': 16, 'status': 'OPEN', 'last_update': 1677010413000}
2023-02-21 20:17:32,646 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:32,648 INFO sqlalchemy.engine.Engine [raw sql] ('Excise Walk', 0, 40, 0, 'dublin', 'EXCISE WALK', 48, 53.347777, -6.244239, 'OPEN')
2023-02-21 20:17:32,773 INFO sqlalchemy.engine.Engine COMMIT
{'number': 13, 'contract_name': 'dublin', 'name': 'FITZWILLIAM SQUARE WEST', 'address': 'Fitzwilliam Square West', 'position': {'lat': 53.336074, 'lng': -6.252825}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 19, 'available_bikes': 11, 'status': 'OPEN', 'last_update': 1677010336000}
2023-02-21 20:17:33,026 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:33,028 INFO sqlalchemy.engine.Engine [raw sql] ('Fitzwilliam Square West', 0, 30, 0, 'dublin', 'FITZWILLIAM SQUARE WEST', 13, 53.336074, -6.252825, 'OPEN')
2023-02-21 20:17:33,149 INFO sqlalchemy.engine.Engine COMMIT
{'number': 43, 'contract_name': 'dublin', 'name': 'PORTOBELLO ROAD', 'address': 'Portobello Road', 'position': {'lat': 53.330091, 'lng': -6.268044}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 1, 'available_bikes': 29, 'status': 'OPEN', 'last_update': 1677010489000}
2023-02-21 20:17:33,389 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:17:33,390 INFO sqlalchemy.engine.Engine [raw sql] ('Portobello Road', 0, 30, 0, 'dublin', 'PORTOBELLO ROAD', 43, 53.330091, -6.268044, 'OPEN')
2023-02-21 20:17:33,510 INFO sqlalchemy.engine.Engine COMMIT
{'number': 31, 'contract_name': 'dublin', 'name': 'PARNELL STREET', 'address': 'Parnell Street', 'position': {'lat': 53.350929, 'lng': -6.265125}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 19, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010399000}
2023-02-21 20:17:33,764 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:33,766 INFO sqlalchemy.engine.Engine [raw sql] ('Parnell Street', 0, 20, 0, 'dublin', 'PARNELL STREET', 31, 53.350929, -6.265125, 'OPEN')
2023-02-21 20:17:33,888 INFO sqlalchemy.engine.Engine COMMIT
{'number': 98, 'contract_name': 'dublin', 'name': 'FREDERICK STREET SOUTH', 'address': 'Frederick Street South', 'position': {'lat': 53.341515, 'lng': -6.256853}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 34, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010063000}
2023-02-21 20:17:34,137 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:34,140 INFO sqlalchemy.engine.Engine [raw sql] ('Frederick Street South', 0, 40, 0, 'dublin', 'FREDERICK STREET SOUTH', 98, 53.341515, -6.256853, 'OPEN')
2023-02-21 20:17:34,260 INFO sqlalchemy.engine.Engine COMMIT
{'number': 14, 'contract_name': 'dublin', 'name': 'FOWNES STREET UPPER', 'address': 'Fownes Street Upper', 'position': {'lat': 53.344603, 'lng': -6.263371}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 7, 'available_bikes': 23, 'status': 'OPEN', 'last_update': 1677010471000}
2023-02-21 20:17:34,516 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:34,517 INFO sqlalchemy.engine.Engine [raw sql] ('Fownes Street Upper', 0, 30, 0, 'dublin', 'FOWNES STREET UPPER', 14, 53.344603, -6.263371, 'OPEN')
2023-02-21 20:17:34,640 INFO sqlalchemy.engine.Engine COMMIT
{'number': 1, 'contract_name': 'dublin', 'name': 'CLARENDON ROW', 'address': 'Clarendon Row', 'position': {'lat': 53.340927, 'lng': -6.262501}, 'banking': False, 'bonus': False, 'bike_stands': 31, 'available_bike_stands': 27, 'available_bikes': 4, 'status': 'OPEN', 'last_update': 1677010185000}
2023-02-21 20:17:34,896 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:34,898 INFO sqlalchemy.engine.Engine [raw sql] ('Clarendon Row', 0, 31, 0, 'dublin', 'CLARENDON ROW', 1, 53.340927, -6.262501, 'OPEN')
2023-02-21 20:17:35,024 INFO sqlalchemy.engine.Engine COMMIT
{'number': 23, 'contract_name': 'dublin', 'name': 'CUSTOM HOUSE', 'address': 'Custom House', 'position': {'lat': 53.348279, 'lng': -6.254662}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 10, 'available_bikes': 20, 'status': 'OPEN', 'last_update': 1677010482000}
2023-02-21 20:17:35,267 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:35,269 INFO sqlalchemy.engine.Engine [raw sql] ('Custom House', 0, 30, 0, 'dublin', 'CUSTOM HOUSE', 23, 53.348279, -6.254662, 'OPEN')
2023-02-21 20:17:35,398 INFO sqlalchemy.engine.Engine COMMIT
{'number': 106, 'contract_name': 'dublin', 'name': 'RATHDOWN ROAD', 'address': 'Rathdown Road', 'position': {'lat': 53.35893, 'lng': -6.280337}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 22, 'available_bikes': 18, 'status': 'OPEN', 'last_update': 1677010505000}
2023-02-21 20:17:35,646 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:35,648 INFO sqlalchemy.engine.Engine [raw sql] ('Rathdown Road', 0, 40, 0, 'dublin', 'RATHDOWN ROAD', 106, 53.35893, -6.280337, 'OPEN')
2023-02-21 20:17:35,769 INFO sqlalchemy.engine.Engine COMMIT
{'number': 112, 'contract_name': 'dublin', 'name': "NORTH CIRCULAR ROAD (O'CONNELL'S)", 'address': "North Circular Road (O'Connell's)", 'position': {'lat': 53.357841, 'lng': -6.251557}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 5, 'available_bikes': 25, 'status': 'OPEN', 'last_update': 1677010637000}
2023-02-21 20:17:36,023 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:36,025 INFO sqlalchemy.engine.Engine [raw sql] ("North Circular Road (O'Connell's)", 0, 30, 0, 'dublin', "NORTH CIRCULAR ROAD (O'CONNELL'S)", 112, 53.357841, -6.251557, 'OPEN')
2023-02-21 20:17:36,149 INFO sqlalchemy.engine.Engine COMMIT
{'number': 68, 'contract_name': 'dublin', 'name': 'HANOVER QUAY', 'address': 'Hanover Quay', 'position': {'lat': 53.344115, 'lng': -6.237153}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 37, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010464000}
2023-02-21 20:17:36,399 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:36,401 INFO sqlalchemy.engine.Engine [raw sql] ('Hanover Quay', 0, 40, 0, 'dublin', 'HANOVER QUAY', 68, 53.344115, -6.237153, 'OPEN')
2023-02-21 20:17:36,521 INFO sqlalchemy.engine.Engine COMMIT
{'number': 74, 'contract_name': 'dublin', 'name': 'OLIVER BOND STREET', 'address': 'Oliver Bond Street', 'position': {'lat': 53.343893, 'lng': -6.280531}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 23, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010520000}
2023-02-21 20:17:36,778 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:36,779 INFO sqlalchemy.engine.Engine [raw sql] ('Oliver Bond Street', 0, 30, 0, 'dublin', 'OLIVER BOND STREET', 74, 53.343893, -6.280531, 'OPEN')
2023-02-21 20:17:36,901 INFO sqlalchemy.engine.Engine COMMIT
{'number': 87, 'contract_name': 'dublin', 'name': 'COLLINS BARRACKS MUSEUM', 'address': 'Collins Barracks Museum', 'position': {'lat': 53.347477, 'lng': -6.28525}, 'banking': False, 'bonus': False, 'bike_stands': 38, 'available_bike_stands': 29, 'available_bikes': 9, 'status': 'OPEN', 'last_update': 1677010197000}
2023-02-21 20:17:37,153 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:37,154 INFO sqlalchemy.engine.Engine [raw sql] ('Collins Barracks Museum', 0, 38, 0, 'dublin', 'COLLINS BARRACKS MUSEUM', 87, 53.347477, -6.28525, 'OPEN')
2023-02-21 20:17:37,278 INFO sqlalchemy.engine.Engine COMMIT
{'number': 84, 'contract_name': 'dublin', 'name': 'BROOKFIELD ROAD', 'address': 'Brookfield Road', 'position': {'lat': 53.339005, 'lng': -6.300217}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 25, 'available_bikes': 5, 'status': 'OPEN', 'last_update': 1677010612000}
2023-02-21 20:17:37,530 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:37,532 INFO sqlalchemy.engine.Engine [raw sql] ('Brookfield Road', 0, 30, 0, 'dublin', 'BROOKFIELD ROAD', 84, 53.339005, -6.300217, 'OPEN')
2023-02-21 20:17:37,655 INFO sqlalchemy.engine.Engine COMMIT
{'number': 90, 'contract_name': 'dublin', 'name': 'BENSON STREET', 'address': 'Benson Street', 'position': {'lat': 53.344153, 'lng': -6.233451}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 40, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010197000}
2023-02-21 20:17:37,909 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:37,911 INFO sqlalchemy.engine.Engine [raw sql] ('Benson Street', 0, 40, 0, 'dublin', 'BENSON STREET', 90, 53.344153, -6.233451, 'OPEN')
2023-02-21 20:17:38,037 INFO sqlalchemy.engine.Engine COMMIT
{'number': 11, 'contract_name': 'dublin', 'name': 'EARLSFORT TERRACE', 'address': 'Earlsfort Terrace', 'position': {'lat': 53.334295, 'lng': -6.258503}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 30, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010477000}
2023-02-21 20:17:38,289 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:17:38,291 INFO sqlalchemy.engine.Engine [raw sql] ('Earlsfort Terrace', 0, 30, 0, 'dublin', 'EARLSFORT TERRACE', 11, 53.334295, -6.258503, 'OPEN')
2023-02-21 20:17:38,411 INFO sqlalchemy.engine.Engine COMMIT
{'number': 17, 'contract_name': 'dublin', 'name': 'GOLDEN LANE', 'address': 'Golden Lane', 'position': {'lat': 53.340803, 'lng': -6.267732}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 13, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010615000}
2023-02-21 20:17:38,660 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:38,662 INFO sqlalchemy.engine.Engine [raw sql] ('Golden Lane', 0, 20, 0, 'dublin', 'GOLDEN LANE', 17, 53.340803, -6.267732, 'OPEN')
2023-02-21 20:17:38,786 INFO sqlalchemy.engine.Engine COMMIT
{'number': 45, 'contract_name': 'dublin', 'name': 'DEVERELL PLACE', 'address': 'Deverell Place', 'position': {'lat': 53.351464, 'lng': -6.255265}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 15, 'available_bikes': 15, 'status': 'OPEN', 'last_update': 1677010342000}
2023-02-21 20:17:39,033 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:39,035 INFO sqlalchemy.engine.Engine [raw sql] ('Deverell Place', 0, 30, 0, 'dublin', 'DEVERELL PLACE', 45, 53.351464, -6.255265, 'OPEN')
2023-02-21 20:17:39,157 INFO sqlalchemy.engine.Engine COMMIT
{'number': 114, 'contract_name': 'dublin', 'name': 'WILTON TERRACE (PARK)', 'address': 'Wilton Terrace (Park)', 'position': {'lat': 53.333653, 'lng': -6.248345}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 39, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010631000}
2023-02-21 20:17:39,411 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:39,412 INFO sqlalchemy.engine.Engine [raw sql] ('Wilton Terrace (Park)', 0, 40, 0, 'dublin', 'WILTON TERRACE (PARK)', 114, 53.333653, -6.248345, 'OPEN')
2023-02-21 20:17:39,537 INFO sqlalchemy.engine.Engine COMMIT
{'number': 72, 'contract_name': 'dublin', 'name': 'JOHN STREET WEST', 'address': 'John Street West', 'position': {'lat': 53.343105, 'lng': -6.277167}, 'banking': False, 'bonus': False, 'bike_stands': 31, 'available_bike_stands': 20, 'available_bikes': 11, 'status': 'OPEN', 'last_update': 1677010435000}
2023-02-21 20:17:39,790 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:39,792 INFO sqlalchemy.engine.Engine [raw sql] ('John Street West', 0, 31, 0, 'dublin', 'JOHN STREET WEST', 72, 53.343105, -6.277167, 'OPEN')
2023-02-21 20:17:39,925 INFO sqlalchemy.engine.Engine COMMIT
{'number': 63, 'contract_name': 'dublin', 'name': 'FENIAN STREET', 'address': 'Fenian Street', 'position': {'lat': 53.341428, 'lng': -6.24672}, 'banking': False, 'bonus': False, 'bike_stands': 35, 'available_bike_stands': 5, 'available_bikes': 30, 'status': 'OPEN', 'last_update': 1677010632000}
2023-02-21 20:17:40,171 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:40,173 INFO sqlalchemy.engine.Engine [raw sql] ('Fenian Street', 0, 35, 0, 'dublin', 'FENIAN STREET', 63, 53.341428, -6.24672, 'OPEN')
2023-02-21 20:17:40,296 INFO sqlalchemy.engine.Engine COMMIT
{'number': 113, 'contract_name': 'dublin', 'name': 'MERRION SQUARE SOUTH', 'address': 'Merrion Square South', 'position': {'lat': 53.338614, 'lng': -6.248606}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 13, 'available_bikes': 27, 'status': 'OPEN', 'last_update': 1677010500000}
2023-02-21 20:17:40,552 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:40,554 INFO sqlalchemy.engine.Engine [raw sql] ('Merrion Square South', 0, 40, 0, 'dublin', 'MERRION SQUARE SOUTH', 113, 53.338614, -6.248606, 'OPEN')
2023-02-21 20:17:40,675 INFO sqlalchemy.engine.Engine COMMIT
{'number': 91, 'contract_name': 'dublin', 'name': 'SOUTH DOCK ROAD', 'address': 'South Dock Road', 'position': {'lat': 53.341833, 'lng': -6.231291}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 9, 'available_bikes': 21, 'status': 'OPEN', 'last_update': 1677010290000}
2023-02-21 20:17:40,921 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:40,922 INFO sqlalchemy.engine.Engine [raw sql] ('South Dock Road', 0, 30, 0, 'dublin', 'SOUTH DOCK ROAD', 91, 53.341833, -6.231291, 'OPEN')
2023-02-21 20:17:41,048 INFO sqlalchemy.engine.Engine COMMIT
{'number': 99, 'contract_name': 'dublin', 'name': 'CITY QUAY', 'address': 'City Quay', 'position': {'lat': 53.346637, 'lng': -6.246154}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 30, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010105000}
2023-02-21 20:17:41,296 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:41,298 INFO sqlalchemy.engine.Engine [raw sql] ('City Quay', 0, 30, 0, 'dublin', 'CITY QUAY', 99, 53.346637, -6.246154, 'OPEN')
2023-02-21 20:17:41,425 INFO sqlalchemy.engine.Engine COMMIT
{'number': 9, 'contract_name': 'dublin', 'name': 'EXCHEQUER STREET', 'address': 'Exchequer Street', 'position': {'lat': 53.343034, 'lng': -6.263578}, 'banking': False, 'bonus': False, 'bike_stands': 24, 'available_bike_stands': 19, 'available_bikes': 5, 'status': 'OPEN', 'last_update': 1677010635000}
2023-02-21 20:17:41,676 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:41,677 INFO sqlalchemy.engine.Engine [raw sql] ('Exchequer Street', 0, 24, 0, 'dublin', 'EXCHEQUER STREET', 9, 53.343034, -6.263578, 'OPEN')
2023-02-21 20:17:41,803 INFO sqlalchemy.engine.Engine COMMIT
{'number': 67, 'contract_name': 'dublin', 'name': 'THE POINT', 'address': 'The Point', 'position': {'lat': 53.346867, 'lng': -6.230852}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 20, 'available_bikes': 20, 'status': 'OPEN', 'last_update': 1677010588000}
2023-02-21 20:17:42,067 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:42,069 INFO sqlalchemy.engine.Engine [raw sql] ('The Point', 0, 40, 0, 'dublin', 'THE POINT', 67, 53.346867, -6.230852, 'OPEN')
2023-02-21 20:17:42,191 INFO sqlalchemy.engine.Engine COMMIT
{'number': 116, 'contract_name': 'dublin', 'name': 'BROADSTONE', 'address': 'Broadstone', 'position': {'lat': 53.3547, 'lng': -6.272314}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 24, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010161000}
2023-02-21 20:17:42,440 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:42,441 INFO sqlalchemy.engine.Engine [raw sql] ('Broadstone', 0, 30, 0, 'dublin', 'BROADSTONE', 116, 53.3547, -6.272314, 'OPEN')
2023-02-21 20:17:42,565 INFO sqlalchemy.engine.Engine COMMIT
{'number': 55, 'contract_name': 'dublin', 'name': 'HATCH STREET', 'address': 'Hatch Street', 'position': {'lat': 53.33403, 'lng': -6.260714}, 'banking': False, 'bonus': False, 'bike_stands': 36, 'available_bike_stands': 31, 'available_bikes': 5, 'status': 'OPEN', 'last_update': 1677010373000}
2023-02-21 20:17:42,813 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:42,816 INFO sqlalchemy.engine.Engine [raw sql] ('Hatch Street', 0, 36, 0, 'dublin', 'HATCH STREET', 55, 53.33403, -6.260714, 'OPEN')
2023-02-21 20:17:42,947 INFO sqlalchemy.engine.Engine COMMIT
{'number': 62, 'contract_name': 'dublin', 'name': 'LIME STREET', 'address': 'Lime Street', 'position': {'lat': 53.346026, 'lng': -6.243576}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 32, 'available_bikes': 8, 'status': 'OPEN', 'last_update': 1677010592000}
2023-02-21 20:17:43,201 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:17:43,203 INFO sqlalchemy.engine.Engine [raw sql] ('Lime Street', 0, 40, 0, 'dublin', 'LIME STREET', 62, 53.346026, -6.243576, 'OPEN')
2023-02-21 20:17:43,325 INFO sqlalchemy.engine.Engine COMMIT
{'number': 5, 'contract_name': 'dublin', 'name': 'CHARLEMONT PLACE', 'address': 'Charlemont Street', 'position': {'lat': 53.330662, 'lng': -6.260177}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 0, 'available_bikes': 40, 'status': 'OPEN', 'last_update': 1677010082000}
2023-02-21 20:17:43,578 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:43,580 INFO sqlalchemy.engine.Engine [raw sql] ('Charlemont Street', 0, 40, 0, 'dublin', 'CHARLEMONT PLACE', 5, 53.330662, -6.260177, 'OPEN')
2023-02-21 20:17:43,703 INFO sqlalchemy.engine.Engine COMMIT
{'number': 97, 'contract_name': 'dublin', 'name': 'KILMAINHAM GAOL', 'address': 'Kilmainham Gaol', 'position': {'lat': 53.342113, 'lng': -6.310015}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 23, 'available_bikes': 17, 'status': 'OPEN', 'last_update': 1677010160000}
2023-02-21 20:17:43,948 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:43,950 INFO sqlalchemy.engine.Engine [raw sql] ('Kilmainham Gaol', 0, 40, 0, 'dublin', 'KILMAINHAM GAOL', 97, 53.342113, -6.310015, 'OPEN')
2023-02-21 20:17:44,073 INFO sqlalchemy.engine.Engine COMMIT
{'number': 61, 'contract_name': 'dublin', 'name': 'HARDWICKE PLACE', 'address': 'Hardwicke Place', 'position': {'lat': 53.357043, 'lng': -6.263232}, 'banking': False, 'bonus': False, 'bike_stands': 25, 'available_bike_stands': 21, 'available_bikes': 4, 'status': 'OPEN', 'last_update': 1677010219000}
2023-02-21 20:17:44,328 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:44,330 INFO sqlalchemy.engine.Engine [raw sql] ('Hardwicke Place', 0, 25, 0, 'dublin', 'HARDWICKE PLACE', 61, 53.357043, -6.263232, 'OPEN')
2023-02-21 20:17:44,452 INFO sqlalchemy.engine.Engine COMMIT
{'number': 77, 'contract_name': 'dublin', 'name': 'WOLFE TONE STREET', 'address': 'Wolfe Tone Street', 'position': {'lat': 53.348875, 'lng': -6.267459}, 'banking': False, 'bonus': False, 'bike_stands': 29, 'available_bike_stands': 23, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010560000}
2023-02-21 20:17:44,710 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:44,711 INFO sqlalchemy.engine.Engine [raw sql] ('Wolfe Tone Street', 0, 29, 0, 'dublin', 'WOLFE TONE STREET', 77, 53.348875, -6.267459, 'OPEN')
2023-02-21 20:17:44,833 INFO sqlalchemy.engine.Engine COMMIT
{'number': 4, 'contract_name': 'dublin', 'name': 'GREEK STREET', 'address': 'Greek Street', 'position': {'lat': 53.346874, 'lng': -6.272976}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 19, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010377000}
2023-02-21 20:17:45,084 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:45,085 INFO sqlalchemy.engine.Engine [raw sql] ('Greek Street', 0, 20, 0, 'dublin', 'GREEK STREET', 4, 53.346874, -6.272976, 'OPEN')
2023-02-21 20:17:45,209 INFO sqlalchemy.engine.Engine COMMIT
{'number': 49, 'contract_name': 'dublin', 'name': 'GUILD STREET', 'address': 'Guild Street', 'position': {'lat': 53.347932, 'lng': -6.240928}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 15, 'available_bikes': 25, 'status': 'OPEN', 'last_update': 1677010613000}
2023-02-21 20:17:45,465 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:45,467 INFO sqlalchemy.engine.Engine [raw sql] ('Guild Street', 0, 40, 0, 'dublin', 'GUILD STREET', 49, 53.347932, -6.240928, 'OPEN')
2023-02-21 20:17:45,598 INFO sqlalchemy.engine.Engine COMMIT
{'number': 19, 'contract_name': 'dublin', 'name': 'HERBERT PLACE', 'address': 'Herbert Place', 'position': {'lat': 53.334432, 'lng': -6.245575}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 27, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010639000}
2023-02-21 20:17:45,848 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:45,850 INFO sqlalchemy.engine.Engine [raw sql] ('Herbert Place', 0, 30, 0, 'dublin', 'HERBERT PLACE', 19, 53.334432, -6.245575, 'OPEN')
2023-02-21 20:17:45,972 INFO sqlalchemy.engine.Engine COMMIT
{'number': 7, 'contract_name': 'dublin', 'name': 'HIGH STREET', 'address': 'High Street', 'position': {'lat': 53.343565, 'lng': -6.275071}, 'banking': False, 'bonus': False, 'bike_stands': 29, 'available_bike_stands': 10, 'available_bikes': 19, 'status': 'OPEN', 'last_update': 1677010337000}
2023-02-21 20:17:46,230 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:46,232 INFO sqlalchemy.engine.Engine [raw sql] ('High Street', 0, 29, 0, 'dublin', 'HIGH STREET', 7, 53.343565, -6.275071, 'OPEN')
2023-02-21 20:17:46,355 INFO sqlalchemy.engine.Engine COMMIT
{'number': 60, 'contract_name': 'dublin', 'name': 'NORTH CIRCULAR ROAD', 'address': 'North Circular Road', 'position': {'lat': 53.359624, 'lng': -6.260348}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 3, 'available_bikes': 27, 'status': 'OPEN', 'last_update': 1677010267000}
2023-02-21 20:17:46,605 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:46,607 INFO sqlalchemy.engine.Engine [raw sql] ('North Circular Road', 0, 30, 0, 'dublin', 'NORTH CIRCULAR ROAD', 60, 53.359624, -6.260348, 'OPEN')
2023-02-21 20:17:46,729 INFO sqlalchemy.engine.Engine COMMIT
{'number': 102, 'contract_name': 'dublin', 'name': 'WESTERN WAY', 'address': 'Western Way', 'position': {'lat': 53.354929, 'lng': -6.269425}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 27, 'available_bikes': 13, 'status': 'OPEN', 'last_update': 1677010295000}
2023-02-21 20:17:46,977 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:46,979 INFO sqlalchemy.engine.Engine [raw sql] ('Western Way', 0, 40, 0, 'dublin', 'WESTERN WAY', 102, 53.354929, -6.269425, 'OPEN')
2023-02-21 20:17:47,100 INFO sqlalchemy.engine.Engine COMMIT
{'number': 38, 'contract_name': 'dublin', 'name': 'TALBOT STREET', 'address': 'Talbot Street', 'position': {'lat': 53.350974, 'lng': -6.25294}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 0, 'available_bikes': 40, 'status': 'OPEN', 'last_update': 1677010446000}
2023-02-21 20:17:47,352 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:47,355 INFO sqlalchemy.engine.Engine [raw sql] ('Talbot Street', 0, 40, 0, 'dublin', 'TALBOT STREET', 38, 53.350974, -6.25294, 'OPEN')
2023-02-21 20:17:47,484 INFO sqlalchemy.engine.Engine COMMIT
{'number': 53, 'contract_name': 'dublin', 'name': 'NEWMAN HOUSE', 'address': 'Newman House', 'position': {'lat': 53.337132, 'lng': -6.26059}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 40, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010496000}
2023-02-21 20:17:47,730 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:47,732 INFO sqlalchemy.engine.Engine [raw sql] ('Newman House', 0, 40, 0, 'dublin', 'NEWMAN HOUSE', 53, 53.337132, -6.26059, 'OPEN')
2023-02-21 20:17:47,856 INFO sqlalchemy.engine.Engine COMMIT
{'number': 58, 'contract_name': 'dublin', 'name': "SIR PATRICK DUN'S", 'address': "Sir Patrick's Dun", 'position': {'lat': 53.339218, 'lng': -6.240642}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 28, 'available_bikes': 12, 'status': 'OPEN', 'last_update': 1677010272000}
2023-02-21 20:17:48,124 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:17:48,126 INFO sqlalchemy.engine.Engine [raw sql] ("Sir Patrick's Dun", 0, 40, 0, 'dublin', "SIR PATRICK DUN'S", 58, 53.339218, -6.240642, 'OPEN')
2023-02-21 20:17:48,248 INFO sqlalchemy.engine.Engine COMMIT
{'number': 66, 'contract_name': 'dublin', 'name': 'NEW CENTRAL BANK', 'address': 'New Central Bank', 'position': {'lat': 53.347122, 'lng': -6.234749}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 33, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010396000}
2023-02-21 20:17:48,494 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:48,496 INFO sqlalchemy.engine.Engine [raw sql] ('New Central Bank', 0, 40, 0, 'dublin', 'NEW CENTRAL BANK', 66, 53.347122, -6.234749, 'OPEN')
2023-02-21 20:17:48,622 INFO sqlalchemy.engine.Engine COMMIT
{'number': 104, 'contract_name': 'dublin', 'name': 'GRANGEGORMAN LOWER (CENTRAL)', 'address': 'Grangegorman Lower (Central)', 'position': {'lat': 53.355173, 'lng': -6.278424}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 39, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010441000}
2023-02-21 20:17:48,874 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:48,876 INFO sqlalchemy.engine.Engine [raw sql] ('Grangegorman Lower (Central)', 0, 40, 0, 'dublin', 'GRANGEGORMAN LOWER (CENTRAL)', 104, 53.355173, -6.278424, 'OPEN')
2023-02-21 20:17:49,000 INFO sqlalchemy.engine.Engine COMMIT
{'number': 101, 'contract_name': 'dublin', 'name': 'KING STREET NORTH', 'address': 'King Street North', 'position': {'lat': 53.350291, 'lng': -6.273507}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 24, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010331000}
2023-02-21 20:17:49,254 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:49,257 INFO sqlalchemy.engine.Engine [raw sql] ('King Street North', 0, 30, 0, 'dublin', 'KING STREET NORTH', 101, 53.350291, -6.273507, 'OPEN')
2023-02-21 20:17:49,377 INFO sqlalchemy.engine.Engine COMMIT
{'number': 115, 'contract_name': 'dublin', 'name': 'KILLARNEY STREET', 'address': 'Killarney Street', 'position': {'lat': 53.354845, 'lng': -6.247579}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 5, 'available_bikes': 25, 'status': 'OPEN', 'last_update': 1677010369000}
2023-02-21 20:17:49,631 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:49,634 INFO sqlalchemy.engine.Engine [raw sql] ('Killarney Street', 0, 30, 0, 'dublin', 'KILLARNEY STREET', 115, 53.354845, -6.247579, 'OPEN')
2023-02-21 20:17:49,759 INFO sqlalchemy.engine.Engine COMMIT
{'number': 47, 'contract_name': 'dublin', 'name': 'HERBERT STREET', 'address': 'Herbert Street', 'position': {'lat': 53.335742, 'lng': -6.24551}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 40, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010380000}
2023-02-21 20:17:50,009 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:50,012 INFO sqlalchemy.engine.Engine [raw sql] ('Herbert Street', 0, 40, 0, 'dublin', 'HERBERT STREET', 47, 53.335742, -6.24551, 'OPEN')
2023-02-21 20:17:50,134 INFO sqlalchemy.engine.Engine COMMIT
{'number': 117, 'contract_name': 'dublin', 'name': 'HANOVER QUAY EAST', 'address': 'Hanover Quay East', 'position': {'lat': 53.343653, 'lng': -6.231755}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 40, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010138000}
2023-02-21 20:17:50,385 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:50,387 INFO sqlalchemy.engine.Engine [raw sql] ('Hanover Quay East', 0, 40, 0, 'dublin', 'HANOVER QUAY EAST', 117, 53.343653, -6.231755, 'OPEN')
2023-02-21 20:17:50,514 INFO sqlalchemy.engine.Engine COMMIT
{'number': 8, 'contract_name': 'dublin', 'name': 'CUSTOM HOUSE QUAY', 'address': 'Custom House Quay', 'position': {'lat': 53.347884, 'lng': -6.248048}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 20, 'available_bikes': 10, 'status': 'OPEN', 'last_update': 1677010599000}
2023-02-21 20:17:50,761 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:50,763 INFO sqlalchemy.engine.Engine [raw sql] ('Custom House Quay', 0, 30, 0, 'dublin', 'CUSTOM HOUSE QUAY', 8, 53.347884, -6.248048, 'OPEN')
2023-02-21 20:17:50,886 INFO sqlalchemy.engine.Engine COMMIT
{'number': 27, 'contract_name': 'dublin', 'name': 'MOLESWORTH STREET', 'address': 'Molesworth Street', 'position': {'lat': 53.341288, 'lng': -6.258117}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 19, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010211000}
2023-02-21 20:17:51,132 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:51,134 INFO sqlalchemy.engine.Engine [raw sql] ('Molesworth Street', 0, 20, 0, 'dublin', 'MOLESWORTH STREET', 27, 53.341288, -6.258117, 'OPEN')
2023-02-21 20:17:51,255 INFO sqlalchemy.engine.Engine COMMIT
{'number': 16, 'contract_name': 'dublin', 'name': 'GEORGES QUAY', 'address': 'Georges Quay', 'position': {'lat': 53.347508, 'lng': -6.252192}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 14, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010105000}
2023-02-21 20:17:51,513 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:51,515 INFO sqlalchemy.engine.Engine [raw sql] ('Georges Quay', 0, 20, 0, 'dublin', 'GEORGES QUAY', 16, 53.347508, -6.252192, 'OPEN')
2023-02-21 20:17:51,638 INFO sqlalchemy.engine.Engine COMMIT
{'number': 96, 'contract_name': 'dublin', 'name': 'KILMAINHAM LANE', 'address': 'Kilmainham Lane', 'position': {'lat': 53.341805, 'lng': -6.305085}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 28, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010529000}
2023-02-21 20:17:51,884 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:51,886 INFO sqlalchemy.engine.Engine [raw sql] ('Kilmainham Lane', 0, 30, 0, 'dublin', 'KILMAINHAM LANE', 96, 53.341805, -6.305085, 'OPEN')
2023-02-21 20:17:52,009 INFO sqlalchemy.engine.Engine COMMIT
{'number': 82, 'contract_name': 'dublin', 'name': 'MOUNT BROWN', 'address': 'Mount Brown', 'position': {'lat': 53.341645, 'lng': -6.29719}, 'banking': False, 'bonus': False, 'bike_stands': 22, 'available_bike_stands': 9, 'available_bikes': 13, 'status': 'OPEN', 'last_update': 1677010179000}
2023-02-21 20:17:52,255 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:52,258 INFO sqlalchemy.engine.Engine [raw sql] ('Mount Brown', 0, 22, 0, 'dublin', 'MOUNT BROWN', 82, 53.341645, -6.29719, 'OPEN')
2023-02-21 20:17:52,379 INFO sqlalchemy.engine.Engine COMMIT
{'number': 76, 'contract_name': 'dublin', 'name': 'MARKET STREET SOUTH', 'address': 'Market Street South', 'position': {'lat': 53.342296, 'lng': -6.287661}, 'banking': False, 'bonus': False, 'bike_stands': 38, 'available_bike_stands': 32, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010262000}
2023-02-21 20:17:52,627 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:52,630 INFO sqlalchemy.engine.Engine [raw sql] ('Market Street South', 0, 38, 0, 'dublin', 'MARKET STREET SOUTH', 76, 53.342296, -6.287661, 'OPEN')
2023-02-21 20:17:52,754 INFO sqlalchemy.engine.Engine COMMIT
{'number': 71, 'contract_name': 'dublin', 'name': 'KEVIN STREET', 'address': 'Kevin Street', 'position': {'lat': 53.337757, 'lng': -6.267699}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 38, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010406000}
2023-02-21 20:17:53,012 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:17:53,014 INFO sqlalchemy.engine.Engine [raw sql] ('Kevin Street', 0, 40, 0, 'dublin', 'KEVIN STREET', 71, 53.337757, -6.267699, 'OPEN')
2023-02-21 20:17:53,136 INFO sqlalchemy.engine.Engine COMMIT
{'number': 79, 'contract_name': 'dublin', 'name': 'ECCLES STREET EAST', 'address': 'Eccles Street East', 'position': {'lat': 53.358115, 'lng': -6.265601}, 'banking': False, 'bonus': False, 'bike_stands': 27, 'available_bike_stands': 25, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010500000}
2023-02-21 20:17:53,389 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:53,391 INFO sqlalchemy.engine.Engine [raw sql] ('Eccles Street East', 0, 27, 0, 'dublin', 'ECCLES STREET EAST', 79, 53.358115, -6.265601, 'OPEN')
2023-02-21 20:17:53,520 INFO sqlalchemy.engine.Engine COMMIT
{'number': 69, 'contract_name': 'dublin', 'name': 'GRAND CANAL DOCK', 'address': 'Grand Canal Dock', 'position': {'lat': 53.342638, 'lng': -6.238695}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 40, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010443000}
2023-02-21 20:17:53,772 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:53,774 INFO sqlalchemy.engine.Engine [raw sql] ('Grand Canal Dock', 0, 40, 0, 'dublin', 'GRAND CANAL DOCK', 69, 53.342638, -6.238695, 'OPEN')
2023-02-21 20:17:53,894 INFO sqlalchemy.engine.Engine COMMIT
{'number': 25, 'contract_name': 'dublin', 'name': 'MERRION SQUARE EAST', 'address': 'Merrion Square East', 'position': {'lat': 53.339434, 'lng': -6.246548}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 27, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010304000}
2023-02-21 20:17:54,158 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:54,160 INFO sqlalchemy.engine.Engine [raw sql] ('Merrion Square East', 0, 30, 0, 'dublin', 'MERRION SQUARE EAST', 25, 53.339434, -6.246548, 'OPEN')
2023-02-21 20:17:54,283 INFO sqlalchemy.engine.Engine COMMIT
{'number': 51, 'contract_name': 'dublin', 'name': 'YORK STREET WEST', 'address': 'York Street West', 'position': {'lat': 53.339334, 'lng': -6.264699}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 38, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010642000}
2023-02-21 20:17:54,541 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:54,543 INFO sqlalchemy.engine.Engine [raw sql] ('York Street West', 0, 40, 0, 'dublin', 'YORK STREET WEST', 51, 53.339334, -6.264699, 'OPEN')
2023-02-21 20:17:54,665 INFO sqlalchemy.engine.Engine COMMIT
{'number': 37, 'contract_name': 'dublin', 'name': "ST. STEPHEN'S GREEN SOUTH", 'address': "St. Stephen's Green South", 'position': {'lat': 53.337494, 'lng': -6.26199}, 'banking': True, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 29, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010075000}
2023-02-21 20:17:54,933 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:54,935 INFO sqlalchemy.engine.Engine [raw sql] ("St. Stephen's Green South", 1, 30, 0, 'dublin', "ST. STEPHEN'S GREEN SOUTH", 37, 53.337494, -6.26199, 'OPEN')
2023-02-21 20:17:55,058 INFO sqlalchemy.engine.Engine COMMIT
{'number': 59, 'contract_name': 'dublin', 'name': 'DENMARK STREET GREAT', 'address': 'Denmark Street Great', 'position': {'lat': 53.35561, 'lng': -6.261397}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 2, 'available_bikes': 18, 'status': 'OPEN', 'last_update': 1677010377000}
2023-02-21 20:17:55,307 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:55,309 INFO sqlalchemy.engine.Engine [raw sql] ('Denmark Street Great', 0, 20, 0, 'dublin', 'DENMARK STREET GREAT', 59, 53.35561, -6.261397, 'OPEN')
2023-02-21 20:17:55,430 INFO sqlalchemy.engine.Engine COMMIT
{'number': 95, 'contract_name': 'dublin', 'name': 'ROYAL HOSPITAL', 'address': 'Royal Hospital', 'position': {'lat': 53.343897, 'lng': -6.29706}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 25, 'available_bikes': 15, 'status': 'OPEN', 'last_update': 1677010107000}
2023-02-21 20:17:55,689 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:55,692 INFO sqlalchemy.engine.Engine [raw sql] ('Royal Hospital', 0, 40, 0, 'dublin', 'ROYAL HOSPITAL', 95, 53.343897, -6.29706, 'OPEN')
2023-02-21 20:17:55,820 INFO sqlalchemy.engine.Engine COMMIT
{'number': 94, 'contract_name': 'dublin', 'name': 'HEUSTON STATION (CAR PARK)', 'address': 'Heuston Station (Car Park)', 'position': {'lat': 53.346985, 'lng': -6.297804}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 34, 'available_bikes': 6, 'status': 'OPEN', 'last_update': 1677010465000}
2023-02-21 20:17:56,077 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:56,079 INFO sqlalchemy.engine.Engine [raw sql] ('Heuston Station (Car Park)', 0, 40, 0, 'dublin', 'HEUSTON STATION (CAR PARK)', 94, 53.346985, -6.297804, 'OPEN')
2023-02-21 20:17:56,201 INFO sqlalchemy.engine.Engine COMMIT
{'number': 105, 'contract_name': 'dublin', 'name': 'GRANGEGORMAN LOWER (NORTH)', 'address': 'Grangegorman Lower (North)', 'position': {'lat': 53.355954, 'lng': -6.278378}, 'banking': False, 'bonus': False, 'bike_stands': 36, 'available_bike_stands': 22, 'available_bikes': 14, 'status': 'OPEN', 'last_update': 1677010403000}
2023-02-21 20:17:56,447 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:56,449 INFO sqlalchemy.engine.Engine [raw sql] ('Grangegorman Lower (North)', 0, 36, 0, 'dublin', 'GRANGEGORMAN LOWER (NORTH)', 105, 53.355954, -6.278378, 'OPEN')
2023-02-21 20:17:56,574 INFO sqlalchemy.engine.Engine COMMIT
{'number': 36, 'contract_name': 'dublin', 'name': "ST. STEPHEN'S GREEN EAST", 'address': "St. Stephen's Green East", 'position': {'lat': 53.337824, 'lng': -6.256035}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 35, 'available_bikes': 5, 'status': 'OPEN', 'last_update': 1677010606000}
2023-02-21 20:17:56,824 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:56,826 INFO sqlalchemy.engine.Engine [raw sql] ("St. Stephen's Green East", 0, 40, 0, 'dublin', "ST. STEPHEN'S GREEN EAST", 36, 53.337824, -6.256035, 'OPEN')
2023-02-21 20:17:56,948 INFO sqlalchemy.engine.Engine COMMIT
{'number': 93, 'contract_name': 'dublin', 'name': 'HEUSTON STATION (CENTRAL)', 'address': 'Heuston Station (Central)', 'position': {'lat': 53.346603, 'lng': -6.296924}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 0, 'available_bikes': 40, 'status': 'OPEN', 'last_update': 1677010469000}
2023-02-21 20:17:57,211 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:57,213 INFO sqlalchemy.engine.Engine [raw sql] ('Heuston Station (Central)', 0, 40, 0, 'dublin', 'HEUSTON STATION (CENTRAL)', 93, 53.346603, -6.296924, 'OPEN')
2023-02-21 20:17:57,335 INFO sqlalchemy.engine.Engine COMMIT
{'number': 22, 'contract_name': 'dublin', 'name': 'TOWNSEND STREET', 'address': 'Townsend Street', 'position': {'lat': 53.345922, 'lng': -6.254614}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 1, 'available_bikes': 18, 'status': 'OPEN', 'last_update': 1677010363000}
2023-02-21 20:17:57,578 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:57,583 INFO sqlalchemy.engine.Engine [raw sql] ('Townsend Street', 0, 20, 0, 'dublin', 'TOWNSEND STREET', 22, 53.345922, -6.254614, 'OPEN')
2023-02-21 20:17:57,714 INFO sqlalchemy.engine.Engine COMMIT

{'number': 50, 'contract_name': 'dublin', 'name': 'GEORGES LANE', 'address': "George's Lane", 'position': {'lat': 53.35023, 'lng': -6.279696}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 10, 'available_bikes': 30, 'status': 'OPEN', 'last_update': 1677010513000}
2023-02-21 20:17:57,973 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:57,975 INFO sqlalchemy.engine.Engine [raw sql] ("George's Lane", 0, 40, 0, 'dublin', 'GEORGES LANE', 50, 53.35023, -6.279696, 'OPEN')
2023-02-21 20:17:58,098 INFO sqlalchemy.engine.Engine COMMIT
{'number': 110, 'contract_name': 'dublin', 'name': 'PHIBSBOROUGH ROAD', 'address': 'Phibsborough Road', 'position': {'lat': 53.356307, 'lng': -6.273717}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 33, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010047000}
2023-02-21 20:17:58,351 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:58,354 INFO sqlalchemy.engine.Engine [raw sql] ('Phibsborough Road', 0, 40, 0, 'dublin', 'PHIBSBOROUGH ROAD', 110, 53.356307, -6.273717, 'OPEN')
2023-02-21 20:17:58,483 INFO sqlalchemy.engine.Engine COMMIT
{'number': 12, 'contract_name': 'dublin', 'name': 'ECCLES STREET', 'address': 'Eccles Street', 'position': {'lat': 53.359246, 'lng': -6.269779}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 13, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010231000}
2023-02-21 20:17:58,729 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:58,732 INFO sqlalchemy.engine.Engine [raw sql] ('Eccles Street', 0, 20, 0, 'dublin', 'ECCLES STREET', 12, 53.359246, -6.269779, 'OPEN')
2023-02-21 20:17:58,862 INFO sqlalchemy.engine.Engine COMMIT
{'number': 34, 'contract_name': 'dublin', 'name': 'PORTOBELLO HARBOUR', 'address': 'Portobello Harbour', 'position': {'lat': 53.330362, 'lng': -6.265163}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 0, 'available_bikes': 30, 'status': 'OPEN', 'last_update': 1677010386000}
2023-02-21 20:17:59,110 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:59,112 INFO sqlalchemy.engine.Engine [raw sql] ('Portobello Harbour', 0, 30, 0, 'dublin', 'PORTOBELLO HARBOUR', 34, 53.330362, -6.265163, 'OPEN')
2023-02-21 20:17:59,236 INFO sqlalchemy.engine.Engine COMMIT
{'number': 78, 'contract_name': 'dublin', 'name': 'MATER HOSPITAL', 'address': 'Mater Hospital', 'position': {'lat': 53.359967, 'lng': -6.264828}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 20, 'available_bikes': 20, 'status': 'OPEN', 'last_update': 1677010188000}
2023-02-21 20:17:59,496 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:59,498 INFO sqlalchemy.engine.Engine [raw sql] ('Mater Hospital', 0, 40, 0, 'dublin', 'MATER HOSPITAL', 78, 53.359967, -6.264828, 'OPEN')
2023-02-21 20:17:59,621 INFO sqlalchemy.engine.Engine COMMIT
{'number': 2, 'contract_name': 'dublin', 'name': 'BLESSINGTON STREET', 'address': 'Blessington Street', 'position': {'lat': 53.356769, 'lng': -6.26814}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 1, 'available_bikes': 19, 'status': 'OPEN', 'last_update': 1677010210000}
2023-02-21 20:17:59,876 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:17:59,879 INFO sqlalchemy.engine.Engine [raw sql] ('Blessington Street', 0, 20, 0, 'dublin', 'BLESSINGTON STREET', 2, 53.356769, -6.26814, 'OPEN')
2023-02-21 20:18:00,003 INFO sqlalchemy.engine.Engine COMMIT
{'number': 75, 'contract_name': 'dublin', 'name': 'JAMES STREET', 'address': 'James Street', 'position': {'lat': 53.343456, 'lng': -6.287409}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 36, 'available_bikes': 4, 'status': 'OPEN', 'last_update': 1677010289000}
2023-02-21 20:18:00,257 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:00,259 INFO sqlalchemy.engine.Engine [raw sql] ('James Street', 0, 40, 0, 'dublin', 'JAMES STREET', 75, 53.343456, -6.287409, 'OPEN')
2023-02-21 20:18:00,380 INFO sqlalchemy.engine.Engine COMMIT
{'number': 507, 'contract_name': 'dublin', 'name': 'ORIEL STREET TEST TERMINAL', 'address': 'JCDecaux Ireland, 52 Oriel Street Lower, Dublin 1', 'position': {'lat': 53.35463, 'lng': -6.242615}, 'banking': False, 'bonus': False, 'bike_stands': 1, 'available_bike_stands': 0, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1675786128000}
2023-02-21 20:18:00,633 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:00,636 INFO sqlalchemy.engine.Engine [raw sql] ('JCDecaux Ireland, 52 Oriel Street Lower, Dublin 1', 0, 1, 0, 'dublin', 'ORIEL STREET TEST TERMINAL', 507, 53.35463, -6.242615, 'OPEN')
2023-02-21 20:18:00,755 INFO sqlalchemy.engine.Engine COMMIT
{'number': 111, 'contract_name': 'dublin', 'name': 'MOUNTJOY SQUARE EAST', 'address': 'Mountjoy Square East', 'position': {'lat': 53.356717, 'lng': -6.256359}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 37, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010647000}
2023-02-21 20:18:01,017 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:01,019 INFO sqlalchemy.engine.Engine [raw sql] ('Mountjoy Square East', 0, 40, 0, 'dublin', 'MOUNTJOY SQUARE EAST', 111, 53.356717, -6.256359, 'OPEN')
2023-02-21 20:18:01,142 INFO sqlalchemy.engine.Engine COMMIT
{'number': 26, 'contract_name': 'dublin', 'name': 'MERRION SQUARE WEST', 'address': 'Merrion Square West', 'position': {'lat': 53.339764, 'lng': -6.251988}, 'banking': True, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 18, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010105000}
2023-02-21 20:18:01,397 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:01,399 INFO sqlalchemy.engine.Engine [raw sql] ('Merrion Square West', 1, 20, 0, 'dublin', 'MERRION SQUARE WEST', 26, 53.339764, -6.251988, 'OPEN')
2023-02-21 20:18:01,522 INFO sqlalchemy.engine.Engine COMMIT
{'number': 65, 'contract_name': 'dublin', 'name': 'CONVENTION CENTRE', 'address': 'Convention Centre', 'position': {'lat': 53.34744, 'lng': -6.238523}, 'banking': True, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 40, 'available_bikes': 0, 'status': 'OPEN', 'last_update': 1677010214000}
2023-02-21 20:18:01,773 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:01,775 INFO sqlalchemy.engine.Engine [raw sql] ('Convention Centre', 1, 40, 0, 'dublin', 'CONVENTION CENTRE', 65, 53.34744, -6.238523, 'OPEN')
2023-02-21 20:18:01,898 INFO sqlalchemy.engine.Engine COMMIT
{'number': 15, 'contract_name': 'dublin', 'name': 'HARDWICKE STREET', 'address': 'Hardwicke Street', 'position': {'lat': 53.355473, 'lng': -6.264423}, 'banking': False, 'bonus': False, 'bike_stands': 16, 'available_bike_stands': 6, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010397000}
2023-02-21 20:18:02,148 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:02,150 INFO sqlalchemy.engine.Engine [raw sql] ('Hardwicke Street', 0, 16, 0, 'dublin', 'HARDWICKE STREET', 15, 53.355473, -6.264423, 'OPEN')
2023-02-21 20:18:02,278 INFO sqlalchemy.engine.Engine COMMIT
{'number': 86, 'contract_name': 'dublin', 'name': 'PARKGATE STREET', 'address': 'Parkgate Street', 'position': {'lat': 53.347972, 'lng': -6.291804}, 'banking': False, 'bonus': False, 'bike_stands': 38, 'available_bike_stands': 1, 'available_bikes': 37, 'status': 'OPEN', 'last_update': 1677010167000}
2023-02-21 20:18:02,525 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:18:02,527 INFO sqlalchemy.engine.Engine [raw sql] ('Parkgate Street', 0, 38, 0, 'dublin', 'PARKGATE STREET', 86, 53.347972, -6.291804, 'OPEN')
2023-02-21 20:18:02,649 INFO sqlalchemy.engine.Engine COMMIT
{'number': 35, 'contract_name': 'dublin', 'name': 'SMITHFIELD', 'address': 'Smithfield', 'position': {'lat': 53.347692, 'lng': -6.278214}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 19, 'available_bikes': 10, 'status': 'OPEN', 'last_update': 1677010541000}
2023-02-21 20:18:02,901 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:02,903 INFO sqlalchemy.engine.Engine [raw sql] ('Smithfield', 0, 30, 0, 'dublin', 'SMITHFIELD', 35, 53.347692, -6.278214, 'OPEN')
2023-02-21 20:18:03,026 INFO sqlalchemy.engine.Engine COMMIT
{'number': 10, 'contract_name': 'dublin', 'name': 'DAME STREET', 'address': 'Dame Street', 'position': {'lat': 53.344007, 'lng': -6.266802}, 'banking': True, 'bonus': False, 'bike_stands': 16, 'available_bike_stands': 2, 'available_bikes': 14, 'status': 'OPEN', 'last_update': 1677010379000}
2023-02-21 20:18:03,286 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:03,290 INFO sqlalchemy.engine.Engine [raw sql] ('Dame Street', 1, 16, 0, 'dublin', 'DAME STREET', 10, 53.344007, -6.266802, 'OPEN')
2023-02-21 20:18:03,413 INFO sqlalchemy.engine.Engine COMMIT
{'number': 100, 'contract_name': 'dublin', 'name': 'HEUSTON BRIDGE (SOUTH)', 'address': 'Heuston Bridge (South)', 'position': {'lat': 53.347106, 'lng': -6.292041}, 'banking': False, 'bonus': False, 'bike_stands': 25, 'available_bike_stands': 0, 'available_bikes': 25, 'status': 'OPEN', 'last_update': 1677010238000}
2023-02-21 20:18:03,660 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:03,662 INFO sqlalchemy.engine.Engine [raw sql] ('Heuston Bridge (South)', 0, 25, 0, 'dublin', 'HEUSTON BRIDGE (SOUTH)', 100, 53.347106, -6.292041, 'OPEN')
2023-02-21 20:18:03,784 INFO sqlalchemy.engine.Engine COMMIT
{'number': 24, 'contract_name': 'dublin', 'name': 'CATHAL BRUGHA STREET', 'address': 'Cathal Brugha Street', 'position': {'lat': 53.352149, 'lng': -6.260533}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 7, 'available_bikes': 13, 'status': 'OPEN', 'last_update': 1677010544000}
2023-02-21 20:18:04,034 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:04,036 INFO sqlalchemy.engine.Engine [raw sql] ('Cathal Brugha Street', 0, 20, 0, 'dublin', 'CATHAL BRUGHA STREET', 24, 53.352149, -6.260533, 'OPEN')
2023-02-21 20:18:04,157 INFO sqlalchemy.engine.Engine COMMIT
{'number': 64, 'contract_name': 'dublin', 'name': 'SANDWITH STREET', 'address': 'Sandwith Street', 'position': {'lat': 53.345203, 'lng': -6.247163}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 10, 'available_bikes': 30, 'status': 'OPEN', 'last_update': 1677010363000}
2023-02-21 20:18:04,405 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:04,408 INFO sqlalchemy.engine.Engine [raw sql] ('Sandwith Street', 0, 40, 0, 'dublin', 'SANDWITH STREET', 64, 53.345203, -6.247163, 'OPEN')
2023-02-21 20:18:04,529 INFO sqlalchemy.engine.Engine COMMIT
{'number': 109, 'contract_name': 'dublin', 'name': 'BUCKINGHAM STREET LOWER', 'address': 'Buckingham Street Lower', 'position': {'lat': 53.353331, 'lng': -6.249319}, 'banking': False, 'bonus': False, 'bike_stands': 29, 'available_bike_stands': 13, 'available_bikes': 16, 'status': 'OPEN', 'last_update': 1677010398000}
2023-02-21 20:18:04,776 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:04,777 INFO sqlalchemy.engine.Engine [raw sql] ('Buckingham Street Lower', 0, 29, 0, 'dublin', 'BUCKINGHAM STREET LOWER', 109, 53.353331, -6.249319, 'OPEN')
2023-02-21 20:18:04,899 INFO sqlalchemy.engine.Engine COMMIT
{'number': 85, 'contract_name': 'dublin', 'name': 'ROTHE ABBEY', 'address': 'Rothe Abbey', 'position': {'lat': 53.338776, 'lng': -6.30395}, 'banking': False, 'bonus': False, 'bike_stands': 35, 'available_bike_stands': 17, 'available_bikes': 18, 'status': 'OPEN', 'last_update': 1677010390000}
2023-02-21 20:18:05,146 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:05,148 INFO sqlalchemy.engine.Engine [raw sql] ('Rothe Abbey', 0, 35, 0, 'dublin', 'ROTHE ABBEY', 85, 53.338776, -6.30395, 'OPEN')
2023-02-21 20:18:05,273 INFO sqlalchemy.engine.Engine COMMIT
{'number': 107, 'contract_name': 'dublin', 'name': 'CHARLEVILLE ROAD', 'address': 'Charleville Road', 'position': {'lat': 53.359157, 'lng': -6.281866}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 25, 'available_bikes': 15, 'status': 'OPEN', 'last_update': 1677010358000}
2023-02-21 20:18:05,528 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:05,531 INFO sqlalchemy.engine.Engine [raw sql] ('Charleville Road', 0, 40, 0, 'dublin', 'CHARLEVILLE ROAD', 107, 53.359157, -6.281866, 'OPEN')
2023-02-21 20:18:05,651 INFO sqlalchemy.engine.Engine COMMIT
{'number': 33, 'contract_name': 'dublin', 'name': "PRINCES STREET / O'CONNELL STREET", 'address': "Princes Street / O'Connell Street", 'position': {'lat': 53.349013, 'lng': -6.260311}, 'banking': True, 'bonus': False, 'bike_stands': 23, 'available_bike_stands': 15, 'available_bikes': 8, 'status': 'OPEN', 'last_update': 1677010604000}
2023-02-21 20:18:05,904 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:05,907 INFO sqlalchemy.engine.Engine [raw sql] ("Princes Street / O'Connell Street", 1, 23, 0, 'dublin', "PRINCES STREET / O'CONNELL STREET", 33, 53.349013, -6.260311, 'OPEN')
2023-02-21 20:18:06,033 INFO sqlalchemy.engine.Engine COMMIT
{'number': 44, 'contract_name': 'dublin', 'name': 'UPPER SHERRARD STREET', 'address': 'Upper Sherrard Street', 'position': {'lat': 53.358437, 'lng': -6.260641}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 26, 'available_bikes': 4, 'status': 'OPEN', 'last_update': 1677010543000}
2023-02-21 20:18:06,311 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:06,313 INFO sqlalchemy.engine.Engine [raw sql] ('Upper Sherrard Street', 0, 30, 0, 'dublin', 'UPPER SHERRARD STREET', 44, 53.358437, -6.260641, 'OPEN')
2023-02-21 20:18:06,441 INFO sqlalchemy.engine.Engine COMMIT
{'number': 89, 'contract_name': 'dublin', 'name': 'FITZWILLIAM SQUARE EAST', 'address': 'Fitzwilliam Square East', 'position': {'lat': 53.335211, 'lng': -6.2509}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 37, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010630000}
2023-02-21 20:18:06,698 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:06,700 INFO sqlalchemy.engine.Engine [raw sql] ('Fitzwilliam Square East', 0, 40, 0, 'dublin', 'FITZWILLIAM SQUARE EAST', 89, 53.335211, -6.2509, 'OPEN')
2023-02-21 20:18:06,830 INFO sqlalchemy.engine.Engine COMMIT
{'number': 57, 'contract_name': 'dublin', 'name': 'GRATTAN STREET', 'address': 'Grattan Street', 'position': {'lat': 53.339629, 'lng': -6.243778}, 'banking': False, 'bonus': False, 'bike_stands': 23, 'available_bike_stands': 6, 'available_bikes': 17, 'status': 'OPEN', 'last_update': 1677010601000}
2023-02-21 20:18:07,084 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:07,087 INFO sqlalchemy.engine.Engine [raw sql] ('Grattan Street', 0, 23, 0, 'dublin', 'GRATTAN STREET', 57, 53.339629, -6.243778, 'OPEN')
2023-02-21 20:18:07,209 INFO sqlalchemy.engine.Engine COMMIT
{'number': 80, 'contract_name': 'dublin', 'name': 'ST JAMES HOSPITAL (LUAS)', 'address': 'St James Hospital (Luas)', 'position': {'lat': 53.341359, 'lng': -6.292951}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 39, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010118000}
2023-02-21 20:18:07,465 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

2023-02-21 20:18:07,468 INFO sqlalchemy.engine.Engine [raw sql] ('St James Hospital (Luas)', 0, 40, 0, 'dublin', 'ST JAMES HOSPITAL (LUAS)', 80, 53.341359, -6.292951, 'OPEN')
2023-02-21 20:18:07,591 INFO sqlalchemy.engine.Engine COMMIT
{'number': 41, 'contract_name': 'dublin', 'name': 'HARCOURT TERRACE', 'address': 'Harcourt Terrace', 'position': {'lat': 53.332763, 'lng': -6.257942}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 1, 'available_bikes': 19, 'status': 'OPEN', 'last_update': 1677010293000}
2023-02-21 20:18:07,846 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:07,849 INFO sqlalchemy.engine.Engine [raw sql] ('Harcourt Terrace', 0, 20, 0, 'dublin', 'HARCOURT TERRACE', 41, 53.332763, -6.257942, 'OPEN')
2023-02-21 20:18:07,977 INFO sqlalchemy.engine.Engine COMMIT
{'number': 3, 'contract_name': 'dublin', 'name': 'BOLTON STREET', 'address': 'Bolton Street', 'position': {'lat': 53.351182, 'lng': -6.269859}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 19, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010382000}
2023-02-21 20:18:08,233 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:08,234 INFO sqlalchemy.engine.Engine [raw sql] ('Bolton Street', 0, 20, 0, 'dublin', 'BOLTON STREET', 3, 53.351182, -6.269859, 'OPEN')
2023-02-21 20:18:08,358 INFO sqlalchemy.engine.Engine COMMIT
{'number': 40, 'contract_name': 'dublin', 'name': 'JERVIS STREET', 'address': 'Jervis Street', 'position': {'lat': 53.3483, 'lng': -6.266651}, 'banking': False, 'bonus': False, 'bike_stands': 21, 'available_bike_stands': 18, 'available_bikes': 3, 'status': 'OPEN', 'last_update': 1677010588000}
2023-02-21 20:18:08,606 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:08,608 INFO sqlalchemy.engine.Engine [raw sql] ('Jervis Street', 0, 21, 0, 'dublin', 'JERVIS STREET', 40, 53.3483, -6.266651, 'OPEN')
2023-02-21 20:18:08,733 INFO sqlalchemy.engine.Engine COMMIT
{'number': 29, 'contract_name': 'dublin', 'name': 'ORMOND QUAY UPPER', 'address': 'Ormond Quay Upper', 'position': {'lat': 53.346057, 'lng': -6.268001}, 'banking': False, 'bonus': False, 'bike_stands': 29, 'available_bike_stands': 27, 'available_bikes': 2, 'status': 'OPEN', 'last_update': 1677010224000}
2023-02-21 20:18:08,988 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:08,991 INFO sqlalchemy.engine.Engine [raw sql] ('Ormond Quay Upper', 0, 29, 0, 'dublin', 'ORMOND QUAY UPPER', 29, 53.346057, -6.268001, 'OPEN')
2023-02-21 20:18:09,122 INFO sqlalchemy.engine.Engine COMMIT
{'number': 103, 'contract_name': 'dublin', 'name': 'GRANGEGORMAN LOWER (SOUTH)', 'address': 'Grangegorman Lower (South)', 'position': {'lat': 53.354663, 'lng': -6.278681}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 39, 'available_bikes': 1, 'status': 'OPEN', 'last_update': 1677010384000}
2023-02-21 20:18:09,382 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:09,388 INFO sqlalchemy.engine.Engine [raw sql] ('Grangegorman Lower (South)', 0, 40, 0, 'dublin', 'GRANGEGORMAN LOWER (SOUTH)', 103, 53.354663, -6.278681, 'OPEN')
2023-02-21 20:18:09,511 INFO sqlalchemy.engine.Engine COMMIT
{'number': 28, 'contract_name': 'dublin', 'name': 'MOUNTJOY SQUARE WEST', 'address': 'Mountjoy Square West', 'position': {'lat': 53.356299, 'lng': -6.258586}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 12, 'available_bikes': 18, 'status': 'OPEN', 'last_update': 1677010294000}
2023-02-21 20:18:09,767 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:09,768 INFO sqlalchemy.engine.Engine [raw sql] ('Mountjoy Square West', 0, 30, 0, 'dublin', 'MOUNTJOY SQUARE WEST', 28, 53.356299, -6.258586, 'OPEN')
2023-02-21 20:18:09,892 INFO sqlalchemy.engine.Engine COMMIT
{'number': 39, 'contract_name': 'dublin', 'name': 'WILTON TERRACE', 'address': 'Wilton Terrace', 'position': {'lat': 53.332383, 'lng': -6.252717}, 'banking': False, 'bonus': False, 'bike_stands': 20, 'available_bike_stands': 11, 'available_bikes': 9, 'status': 'OPEN', 'last_update': 1677010217000}
2023-02-21 20:18:10,156 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:10,158 INFO sqlalchemy.engine.Engine [raw sql] ('Wilton Terrace', 0, 20, 0, 'dublin', 'WILTON TERRACE', 39, 53.332383, -6.252717, 'OPEN')
2023-02-21 20:18:10,281 INFO sqlalchemy.engine.Engine COMMIT
{'number': 83, 'contract_name': 'dublin', 'name': 'EMMET ROAD', 'address': 'Emmet Road', 'position': {'lat': 53.340714, 'lng': -6.308191}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 15, 'available_bikes': 25, 'status': 'OPEN', 'last_update': 1677010216000}
2023-02-21 20:18:10,529 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:10,531 INFO sqlalchemy.engine.Engine [raw sql] ('Emmet Road', 0, 40, 0, 'dublin', 'EMMET ROAD', 83, 53.340714, -6.308191, 'OPEN')
2023-02-21 20:18:10,656 INFO sqlalchemy.engine.Engine COMMIT
{'number': 92, 'contract_name': 'dublin', 'name': 'HEUSTON BRIDGE (NORTH)', 'address': 'Heuston Bridge (North)', 'position': {'lat': 53.347802, 'lng': -6.292432}, 'banking': False, 'bonus': False, 'bike_stands': 40, 'available_bike_stands': 0, 'available_bikes': 40, 'status': 'OPEN', 'last_update': 1677010602000}
2023-02-21 20:18:10,909 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:10,911 INFO sqlalchemy.engine.Engine [raw sql] ('Heuston Bridge (North)', 0, 40, 0, 'dublin', 'HEUSTON BRIDGE (NORTH)', 92, 53.347802, -6.292432, 'OPEN')
2023-02-21 20:18:11,039 INFO sqlalchemy.engine.Engine COMMIT
{'number': 21, 'contract_name': 'dublin', 'name': 'LEINSTER STREET SOUTH', 'address': 'Leinster Street South', 'position': {'lat': 53.34218, 'lng': -6.254485}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 23, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010256000}
2023-02-21 20:18:11,296 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:11,298 INFO sqlalchemy.engine.Engine [raw sql] ('Leinster Street South', 0, 30, 0, 'dublin', 'LEINSTER STREET SOUTH', 21, 53.34218, -6.254485, 'OPEN')
2023-02-21 20:18:11,420 INFO sqlalchemy.engine.Engine COMMIT
{'number': 88, 'contract_name': 'dublin', 'name': 'BLACKHALL PLACE', 'address': 'Blackhall Place', 'position': {'lat': 53.3488, 'lng': -6.281637}, 'banking': False, 'bonus': False, 'bike_stands': 30, 'available_bike_stands': 23, 'available_bikes': 7, 'status': 'OPEN', 'last_update': 1677010175000}
2023-02-21 20:18:11,671 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`station` values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
2023-02-21 20:18:11,674 INFO sqlalchemy.engine.Engine [raw sql] ('Blackhall Place', 0, 30, 0, 'dublin', 'BLACKHALL PLACE', 88, 53.3488, -6.281637, 'OPEN')
2023-02-21 20:18:11,797 INFO sqlalchemy.engine.Engine COMMIT
2023-02-21 20:18:12,050 INFO sqlalchemy.engine.Engine INSERT INTO `dublin_bikes`.`availability` values(%s,%s,%s,%s)
2023-02-21 20:18:12,052 INFO sqlalchemy.engine.Engine [raw sql] (42, 29, 1, 1677010068000)
2023-02-21 20:18:12,204 INFO sqlalchemy.engine.Engine ROLLBACK
Traceback (most recent call last):
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'dublin_bikes.availability' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/folders/fq/bzr8_90x2fz7g47x1rk7l_tm0000gn/T/ipykernel_7166/3784899699.py", line 42, in main
    availability_to_db(r.text)
  File "/var/folders/fq/bzr8_90x2fz7g47x1rk7l_tm0000gn/T/ipykernel_7166/3784899699.py", line 29, in availability_to_db
    engine.execute("INSERT INTO `dublin_bikes`.`availability` values(%s,%s,%s,%s)", vals)
  File "<string>", line 2, in execute
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 402, in warned
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3176, in execute
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1291, in execute
    def _execute_function(self, func, multiparams, params, execution_options):
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1595, in _exec_driver_sql
    execution_options,
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    if self._has_events or self.engine._has_events:
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    self.close()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    finally:
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/Users/conormcelduff/opt/anaconda3/envs/comp30830/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'dublin_bikes.availability' doesn't exist")
[SQL: INSERT INTO `dublin_bikes`.`availability` values(%s,%s,%s,%s)]
[parameters: (42, 29, 1, 1677010068000)]
(Background on this error at: https://sqlalche.me/e/14/f405)

In [51]:
NAME="Dublin"
STATIONS="https://api.jcdecaux.com/vls/v1/stations"
r = requests.get(STATIONS, params={"contract" : NAME, "apiKey": DubBike_API})

In [52]:
r.json()

[{'number': 42,
  'contract_name': 'dublin',
  'name': 'SMITHFIELD NORTH',
  'address': 'Smithfield North',
  'position': {'lat': 53.349562, 'lng': -6.278198},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 1,
  'available_bikes': 29,
  'status': 'OPEN',
  'last_update': 1677010675000},
 {'number': 30,
  'contract_name': 'dublin',
  'name': 'PARNELL SQUARE NORTH',
  'address': 'Parnell Square North',
  'position': {'lat': 53.3537415547453, 'lng': -6.26530144781526},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 18,
  'available_bikes': 2,
  'status': 'OPEN',
  'last_update': 1677010659000},
 {'number': 54,
  'contract_name': 'dublin',
  'name': 'CLONMEL STREET',
  'address': 'Clonmel Street',
  'position': {'lat': 53.336021, 'lng': -6.26298},
  'banking': False,
  'bonus': False,
  'bike_stands': 33,
  'available_bike_stands': 27,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010624000},
 {'number': 108,
  'contract_name': 'dublin',
  'name': 'AVONDALE ROAD',
  'address': 'Avondale Road',
  'position': {'lat': 53.359405, 'lng': -6.276142},
  'banking': False,
  'bonus': False,
  'bike_stands': 35,
  'available_bike_stands': 20,
  'available_bikes': 15,
  'status': 'OPEN',
  'last_update': 1677010205000},
 {'number': 20,
  'contract_name': 'dublin',
  'name': 'JAMES STREET EAST',
  'address': 'James Street East',
  'position': {'lat': 53.336597, 'lng': -6.248109},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 27,
  'available_bikes': 3,
  'status': 'OPEN',
  'last_update': 1677010117000},
 {'number': 56,
  'contract_name': 'dublin',
  'name': 'MOUNT STREET LOWER',
  'address': 'Mount Street Lower',
  'position': {'lat': 53.33796, 'lng': -6.24153},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 37,
  'available_bikes': 3,
  'status': 'OPEN',
  'last_update': 1677010421000},
 {'number': 6,
  'contract_name': 'dublin',
  'name': 'CHRISTCHURCH PLACE',
  'address': 'Christchurch Place',
  'position': {'lat': 53.343368, 'lng': -6.27012},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 14,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010617000},
 {'number': 18,
  'contract_name': 'dublin',
  'name': 'GRANTHAM STREET',
  'address': 'Grantham Street',
  'position': {'lat': 53.334123, 'lng': -6.265436},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 5,
  'available_bikes': 25,
  'status': 'OPEN',
  'last_update': 1677010637000},
 {'number': 32,
  'contract_name': 'dublin',
  'name': 'PEARSE STREET',
  'address': 'Pearse Street',
  'position': {'lat': 53.344304, 'lng': -6.250427},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 0,
  'available_bikes': 30,
  'status': 'OPEN',
  'last_update': 1677010588000},
 {'number': 52,
  'contract_name': 'dublin',
  'name': 'YORK STREET EAST',
  'address': 'York Street East',
  'position': {'lat': 53.338755, 'lng': -6.262003},
  'banking': False,
  'bonus': False,
  'bike_stands': 32,
  'available_bike_stands': 28,
  'available_bikes': 4,
  'status': 'OPEN',
  'last_update': 1677010663000},
 {'number': 48,
  'contract_name': 'dublin',
  'name': 'EXCISE WALK',
  'address': 'Excise Walk',
  'position': {'lat': 53.347777, 'lng': -6.244239},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 24,
  'available_bikes': 16,
  'status': 'OPEN',
  'last_update': 1677010413000},
 {'number': 13,
  'contract_name': 'dublin',
  'name': 'FITZWILLIAM SQUARE WEST',
  'address': 'Fitzwilliam Square West',
  'position': {'lat': 53.336074, 'lng': -6.252825},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 19,
  'available_bikes': 11,
  'status': 'OPEN',
  'last_update': 1677010336000},
 {'number': 43,
  'contract_name': 'dublin',
  'name': 'PORTOBELLO ROAD',
  'address': 'Portobello Road',
  'position': {'lat': 53.330091, 'lng': -6.268044},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 0,
  'available_bikes': 30,
  'status': 'OPEN',
  'last_update': 1677010651000},
 {'number': 31,
  'contract_name': 'dublin',
  'name': 'PARNELL STREET',
  'address': 'Parnell Street',
  'position': {'lat': 53.350929, 'lng': -6.265125},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 20,
  'available_bikes': 0,
  'status': 'OPEN',
  'last_update': 1677010682000},
 {'number': 98,
  'contract_name': 'dublin',
  'name': 'FREDERICK STREET SOUTH',
  'address': 'Frederick Street South',
  'position': {'lat': 53.341515, 'lng': -6.256853},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 34,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010670000},
 {'number': 14,
  'contract_name': 'dublin',
  'name': 'FOWNES STREET UPPER',
  'address': 'Fownes Street Upper',
  'position': {'lat': 53.344603, 'lng': -6.263371},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 7,
  'available_bikes': 23,
  'status': 'OPEN',
  'last_update': 1677010471000},
 {'number': 1,
  'contract_name': 'dublin',
  'name': 'CLARENDON ROW',
  'address': 'Clarendon Row',
  'position': {'lat': 53.340927, 'lng': -6.262501},
  'banking': False,
  'bonus': False,
  'bike_stands': 31,
  'available_bike_stands': 26,
  'available_bikes': 5,
  'status': 'OPEN',
  'last_update': 1677010700000},
 {'number': 23,
  'contract_name': 'dublin',
  'name': 'CUSTOM HOUSE',
  'address': 'Custom House',
  'position': {'lat': 53.348279, 'lng': -6.254662},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 10,
  'available_bikes': 20,
  'status': 'OPEN',
  'last_update': 1677010482000},
 {'number': 106,
  'contract_name': 'dublin',
  'name': 'RATHDOWN ROAD',
  'address': 'Rathdown Road',
  'position': {'lat': 53.35893, 'lng': -6.280337},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 22,
  'available_bikes': 18,
  'status': 'OPEN',
  'last_update': 1677010505000},
 {'number': 112,
  'contract_name': 'dublin',
  'name': "NORTH CIRCULAR ROAD (O'CONNELL'S)",
  'address': "North Circular Road (O'Connell's)",
  'position': {'lat': 53.357841, 'lng': -6.251557},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 5,
  'available_bikes': 25,
  'status': 'OPEN',
  'last_update': 1677010637000},
 {'number': 68,
  'contract_name': 'dublin',
  'name': 'HANOVER QUAY',
  'address': 'Hanover Quay',
  'position': {'lat': 53.344115, 'lng': -6.237153},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 38,
  'available_bikes': 2,
  'status': 'OPEN',
  'last_update': 1677010677000},
 {'number': 74,
  'contract_name': 'dublin',
  'name': 'OLIVER BOND STREET',
  'address': 'Oliver Bond Street',
  'position': {'lat': 53.343893, 'lng': -6.280531},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 23,
  'available_bikes': 7,
  'status': 'OPEN',
  'last_update': 1677010520000},
 {'number': 87,
  'contract_name': 'dublin',
  'name': 'COLLINS BARRACKS MUSEUM',
  'address': 'Collins Barracks Museum',
  'position': {'lat': 53.347477, 'lng': -6.28525},
  'banking': False,
  'bonus': False,
  'bike_stands': 38,
  'available_bike_stands': 29,
  'available_bikes': 9,
  'status': 'OPEN',
  'last_update': 1677010197000},
 {'number': 84,
  'contract_name': 'dublin',
  'name': 'BROOKFIELD ROAD',
  'address': 'Brookfield Road',
  'position': {'lat': 53.339005, 'lng': -6.300217},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 25,
  'available_bikes': 5,
  'status': 'OPEN',
  'last_update': 1677010612000},
 {'number': 90,
  'contract_name': 'dublin',
  'name': 'BENSON STREET',
  'address': 'Benson Street',
  'position': {'lat': 53.344153, 'lng': -6.233451},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 39,
  'available_bikes': 1,
  'status': 'OPEN',
  'last_update': 1677010707000},
 {'number': 11,
  'contract_name': 'dublin',
  'name': 'EARLSFORT TERRACE',
  'address': 'Earlsfort Terrace',
  'position': {'lat': 53.334295, 'lng': -6.258503},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 30,
  'available_bikes': 0,
  'status': 'OPEN',
  'last_update': 1677010477000},
 {'number': 17,
  'contract_name': 'dublin',
  'name': 'GOLDEN LANE',
  'address': 'Golden Lane',
  'position': {'lat': 53.340803, 'lng': -6.267732},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 13,
  'available_bikes': 7,
  'status': 'OPEN',
  'last_update': 1677010615000},
 {'number': 45,
  'contract_name': 'dublin',
  'name': 'DEVERELL PLACE',
  'address': 'Deverell Place',
  'position': {'lat': 53.351464, 'lng': -6.255265},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 15,
  'available_bikes': 15,
  'status': 'OPEN',
  'last_update': 1677010342000},
 {'number': 114,
  'contract_name': 'dublin',
  'name': 'WILTON TERRACE (PARK)',
  'address': 'Wilton Terrace (Park)',
  'position': {'lat': 53.333653, 'lng': -6.248345},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 39,
  'available_bikes': 1,
  'status': 'OPEN',
  'last_update': 1677010631000},
 {'number': 72,
  'contract_name': 'dublin',
  'name': 'JOHN STREET WEST',
  'address': 'John Street West',
  'position': {'lat': 53.343105, 'lng': -6.277167},
  'banking': False,
  'bonus': False,
  'bike_stands': 31,
  'available_bike_stands': 20,
  'available_bikes': 11,
  'status': 'OPEN',
  'last_update': 1677010435000},
 {'number': 63,
  'contract_name': 'dublin',
  'name': 'FENIAN STREET',
  'address': 'Fenian Street',
  'position': {'lat': 53.341428, 'lng': -6.24672},
  'banking': False,
  'bonus': False,
  'bike_stands': 35,
  'available_bike_stands': 5,
  'available_bikes': 30,
  'status': 'OPEN',
  'last_update': 1677010632000},
 {'number': 113,
  'contract_name': 'dublin',
  'name': 'MERRION SQUARE SOUTH',
  'address': 'Merrion Square South',
  'position': {'lat': 53.338614, 'lng': -6.248606},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 13,
  'available_bikes': 27,
  'status': 'OPEN',
  'last_update': 1677010500000},
 {'number': 91,
  'contract_name': 'dublin',
  'name': 'SOUTH DOCK ROAD',
  'address': 'South Dock Road',
  'position': {'lat': 53.341833, 'lng': -6.231291},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 9,
  'available_bikes': 21,
  'status': 'OPEN',
  'last_update': 1677010290000},
 {'number': 99,
  'contract_name': 'dublin',
  'name': 'CITY QUAY',
  'address': 'City Quay',
  'position': {'lat': 53.346637, 'lng': -6.246154},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 30,
  'available_bikes': 0,
  'status': 'OPEN',
  'last_update': 1677010105000},
 {'number': 9,
  'contract_name': 'dublin',
  'name': 'EXCHEQUER STREET',
  'address': 'Exchequer Street',
  'position': {'lat': 53.343034, 'lng': -6.263578},
  'banking': False,
  'bonus': False,
  'bike_stands': 24,
  'available_bike_stands': 19,
  'available_bikes': 5,
  'status': 'OPEN',
  'last_update': 1677010635000},
 {'number': 67,
  'contract_name': 'dublin',
  'name': 'THE POINT',
  'address': 'The Point',
  'position': {'lat': 53.346867, 'lng': -6.230852},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 20,
  'available_bikes': 20,
  'status': 'OPEN',
  'last_update': 1677010588000},
 {'number': 116,
  'contract_name': 'dublin',
  'name': 'BROADSTONE',
  'address': 'Broadstone',
  'position': {'lat': 53.3547, 'lng': -6.272314},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 24,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010161000},
 {'number': 55,
  'contract_name': 'dublin',
  'name': 'HATCH STREET',
  'address': 'Hatch Street',
  'position': {'lat': 53.33403, 'lng': -6.260714},
  'banking': False,
  'bonus': False,
  'bike_stands': 36,
  'available_bike_stands': 31,
  'available_bikes': 5,
  'status': 'OPEN',
  'last_update': 1677010373000},
 {'number': 62,
  'contract_name': 'dublin',
  'name': 'LIME STREET',
  'address': 'Lime Street',
  'position': {'lat': 53.346026, 'lng': -6.243576},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 33,
  'available_bikes': 7,
  'status': 'OPEN',
  'last_update': 1677010698000},
 {'number': 5,
  'contract_name': 'dublin',
  'name': 'CHARLEMONT PLACE',
  'address': 'Charlemont Street',
  'position': {'lat': 53.330662, 'lng': -6.260177},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 0,
  'available_bikes': 40,
  'status': 'OPEN',
  'last_update': 1677010688000},
 {'number': 97,
  'contract_name': 'dublin',
  'name': 'KILMAINHAM GAOL',
  'address': 'Kilmainham Gaol',
  'position': {'lat': 53.342113, 'lng': -6.310015},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 23,
  'available_bikes': 17,
  'status': 'OPEN',
  'last_update': 1677010160000},
 {'number': 61,
  'contract_name': 'dublin',
  'name': 'HARDWICKE PLACE',
  'address': 'Hardwicke Place',
  'position': {'lat': 53.357043, 'lng': -6.263232},
  'banking': False,
  'bonus': False,
  'bike_stands': 25,
  'available_bike_stands': 21,
  'available_bikes': 4,
  'status': 'OPEN',
  'last_update': 1677010219000},
 {'number': 77,
  'contract_name': 'dublin',
  'name': 'WOLFE TONE STREET',
  'address': 'Wolfe Tone Street',
  'position': {'lat': 53.348875, 'lng': -6.267459},
  'banking': False,
  'bonus': False,
  'bike_stands': 29,
  'available_bike_stands': 23,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010560000},
 {'number': 4,
  'contract_name': 'dublin',
  'name': 'GREEK STREET',
  'address': 'Greek Street',
  'position': {'lat': 53.346874, 'lng': -6.272976},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 19,
  'available_bikes': 1,
  'status': 'OPEN',
  'last_update': 1677010377000},
 {'number': 49,
  'contract_name': 'dublin',
  'name': 'GUILD STREET',
  'address': 'Guild Street',
  'position': {'lat': 53.347932, 'lng': -6.240928},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 17,
  'available_bikes': 23,
  'status': 'OPEN',
  'last_update': 1677010701000},
 {'number': 19,
  'contract_name': 'dublin',
  'name': 'HERBERT PLACE',
  'address': 'Herbert Place',
  'position': {'lat': 53.334432, 'lng': -6.245575},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 27,
  'available_bikes': 3,
  'status': 'OPEN',
  'last_update': 1677010639000},
 {'number': 7,
  'contract_name': 'dublin',
  'name': 'HIGH STREET',
  'address': 'High Street',
  'position': {'lat': 53.343565, 'lng': -6.275071},
  'banking': False,
  'bonus': False,
  'bike_stands': 29,
  'available_bike_stands': 10,
  'available_bikes': 19,
  'status': 'OPEN',
  'last_update': 1677010337000},
 {'number': 60,
  'contract_name': 'dublin',
  'name': 'NORTH CIRCULAR ROAD',
  'address': 'North Circular Road',
  'position': {'lat': 53.359624, 'lng': -6.260348},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 3,
  'available_bikes': 27,
  'status': 'OPEN',
  'last_update': 1677010267000},
 {'number': 102,
  'contract_name': 'dublin',
  'name': 'WESTERN WAY',
  'address': 'Western Way',
  'position': {'lat': 53.354929, 'lng': -6.269425},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 27,
  'available_bikes': 13,
  'status': 'OPEN',
  'last_update': 1677010295000},
 {'number': 38,
  'contract_name': 'dublin',
  'name': 'TALBOT STREET',
  'address': 'Talbot Street',
  'position': {'lat': 53.350974, 'lng': -6.25294},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 0,
  'available_bikes': 40,
  'status': 'OPEN',
  'last_update': 1677010446000},
 {'number': 53,
  'contract_name': 'dublin',
  'name': 'NEWMAN HOUSE',
  'address': 'Newman House',
  'position': {'lat': 53.337132, 'lng': -6.26059},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 40,
  'available_bikes': 0,
  'status': 'OPEN',
  'last_update': 1677010496000},
 {'number': 58,
  'contract_name': 'dublin',
  'name': "SIR PATRICK DUN'S",
  'address': "Sir Patrick's Dun",
  'position': {'lat': 53.339218, 'lng': -6.240642},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 30,
  'available_bikes': 10,
  'status': 'OPEN',
  'last_update': 1677010706000},
 {'number': 66,
  'contract_name': 'dublin',
  'name': 'NEW CENTRAL BANK',
  'address': 'New Central Bank',
  'position': {'lat': 53.347122, 'lng': -6.234749},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 33,
  'available_bikes': 7,
  'status': 'OPEN',
  'last_update': 1677010396000},
 {'number': 104,
  'contract_name': 'dublin',
  'name': 'GRANGEGORMAN LOWER (CENTRAL)',
  'address': 'Grangegorman Lower (Central)',
  'position': {'lat': 53.355173, 'lng': -6.278424},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 39,
  'available_bikes': 1,
  'status': 'OPEN',
  'last_update': 1677010441000},
 {'number': 101,
  'contract_name': 'dublin',
  'name': 'KING STREET NORTH',
  'address': 'King Street North',
  'position': {'lat': 53.350291, 'lng': -6.273507},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 24,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010331000},
 {'number': 115,
  'contract_name': 'dublin',
  'name': 'KILLARNEY STREET',
  'address': 'Killarney Street',
  'position': {'lat': 53.354845, 'lng': -6.247579},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 5,
  'available_bikes': 25,
  'status': 'OPEN',
  'last_update': 1677010369000},
 {'number': 47,
  'contract_name': 'dublin',
  'name': 'HERBERT STREET',
  'address': 'Herbert Street',
  'position': {'lat': 53.335742, 'lng': -6.24551},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 40,
  'available_bikes': 0,
  'status': 'OPEN',
  'last_update': 1677010380000},
 {'number': 117,
  'contract_name': 'dublin',
  'name': 'HANOVER QUAY EAST',
  'address': 'Hanover Quay East',
  'position': {'lat': 53.343653, 'lng': -6.231755},
  'banking': False,
  'bonus': False,
  'bike_stands': 40,
  'available_bike_stands': 40,
  'available_bikes': 0,
  'status': 'OPEN',
  'last_update': 1677010138000},
 {'number': 8,
  'contract_name': 'dublin',
  'name': 'CUSTOM HOUSE QUAY',
  'address': 'Custom House Quay',
  'position': {'lat': 53.347884, 'lng': -6.248048},
  'banking': False,
  'bonus': False,
  'bike_stands': 30,
  'available_bike_stands': 20,
  'available_bikes': 10,
  'status': 'OPEN',
  'last_update': 1677010599000},
 {'number': 27,
  'contract_name': 'dublin',
  'name': 'MOLESWORTH STREET',
  'address': 'Molesworth Street',
  'position': {'lat': 53.341288, 'lng': -6.258117},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 19,
  'available_bikes': 1,
  'status': 'OPEN',
  'last_update': 1677010211000},
 {'number': 16,
  'contract_name': 'dublin',
  'name': 'GEORGES QUAY',
  'address': 'Georges Quay',
  'position': {'lat': 53.347508, 'lng': -6.252192},
  'banking': False,
  'bonus': False,
  'bike_stands': 20,
  'available_bike_stands': 14,
  'available_bikes': 6,
  'status': 'OPEN',
  'last_update': 1677010105000},
 {'number': 96,
  'contract_name': 'dublin',
  'name': 'KILMAINHAM LANE',